// PDF generation using jsPDF + html2canvas (fixes blank PDF bug)
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

export async function generatePDF(elementId, filename, isPremium = false) {
    const element = document.getElementById(elementId);
    if (!element) {
        console.error('PDF element not found:', elementId);
        return;
    }

    // Clone and place off-screen
    const clone = element.cloneNode(true);
    clone.style.cssText = `
        position: fixed;
        top: 0;
        left: -9999px;
        width: 794px;
        min-height: 1123px;
        background: white;
        color: black;
        z-index: -9999;
        transform: none;
        padding: 40px;
        box-sizing: border-box;
        font-family: 'Plus Jakarta Sans', Arial, sans-serif;
    `;

    // Force all text black in clone
    const allEls = clone.querySelectorAll('*');
    allEls.forEach(el => {
        const computed = window.getComputedStyle(el);
        el.style.color = '#000000';
        el.style.webkitTextFillColor = '#000000';
        // Keep background colours except white/transparent
        const bg = computed.backgroundColor;
        if (!bg || bg === 'rgba(0, 0, 0, 0)' || bg === 'transparent') {
            el.style.backgroundColor = 'transparent';
        }
    });

    // Add watermark for FREE users
    if (!isPremium) {
        const wm = document.createElement('div');
        wm.style.cssText = `
            position: absolute; bottom: 16px; left: 50%;
            transform: translateX(-50%); font-size: 11px;
            color: rgba(100,116,139,0.5);
            font-family: 'Plus Jakarta Sans', Arial, sans-serif;
            white-space: nowrap; pointer-events: none;
        `;
        wm.textContent = 'Generated by MyInvoice.space';
        clone.style.position = 'fixed'; // ensure relative works
        clone.style.position = 'fixed';
        clone.appendChild(wm);
    }

    document.body.appendChild(clone);

    // Wait for fonts/images to settle
    await new Promise(r => setTimeout(r, 800));

    try {
        const canvas = await html2canvas(clone, {
            scale: 2,
            useCORS: true,
            allowTaint: true,
            logging: false,
            backgroundColor: '#ffffff',
            width: 794,
            windowWidth: 794,
            windowHeight: clone.scrollHeight,
        });

        const imgData = canvas.toDataURL('image/jpeg', 0.98);
        const pdf = new jsPDF({
            orientation: 'portrait',
            unit: 'mm',
            format: 'a4',
            compress: true,
        });

        const pdfWidth = pdf.internal.pageSize.getWidth();
        const pdfHeight = pdf.internal.pageSize.getHeight();
        const imgWidth = pdfWidth;
        const imgHeight = (canvas.height * pdfWidth) / canvas.width;

        if (imgHeight <= pdfHeight) {
            pdf.addImage(imgData, 'JPEG', 0, 0, imgWidth, imgHeight);
        } else {
            let heightLeft = imgHeight;
            let position = 0;
            pdf.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
            heightLeft -= pdfHeight;
            while (heightLeft > 0) {
                position = heightLeft - imgHeight;
                pdf.addPage();
                pdf.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
                heightLeft -= pdfHeight;
            }
        }

        pdf.save((filename || 'document') + (filename?.endsWith('.pdf') ? '' : '.pdf'));
    } finally {
        document.body.removeChild(clone);
    }
}
