// PDF generation using html2pdf.js
export async function generatePDF(elementId, filename, isPro = false) {
    const html2pdf = (await import('html2pdf.js')).default;

    const originalEl = document.getElementById(elementId);
    if (!originalEl) {
        console.error('Element not found:', elementId);
        return;
    }

    // Clone and prepare off-screen
    const clone = originalEl.cloneNode(true);
    clone.style.width = '794px';
    clone.style.transform = 'none';
    clone.style.position = 'absolute';
    clone.style.left = '-9999px';
    clone.style.top = '0';
    clone.style.padding = '0';
    clone.style.margin = '0';
    clone.style.boxShadow = 'none';
    clone.style.borderRadius = '0';
    clone.style.background = 'white';
    clone.style.color = '#000';

    // Add watermark for FREE users
    if (!isPro) {
        const watermark = document.createElement('div');
        watermark.style.cssText = `
      position: absolute; bottom: 20px; left: 50%;
      transform: translateX(-50%); font-size: 11px;
      color: rgba(100,116,139,0.5); font-family: 'Plus Jakarta Sans', sans-serif;
      white-space: nowrap; z-index: 9999; pointer-events: none;
    `;
        watermark.textContent = 'Generated by MyInvoice.space';
        clone.style.position = 'relative';
        clone.appendChild(watermark);
    }

    document.body.appendChild(clone);

    // Wait for fonts/images to load
    await new Promise(r => setTimeout(r, 500));

    await html2pdf()
        .set({
            margin: [10, 10, 10, 10],
            filename: filename || 'document.pdf',
            image: { type: 'jpeg', quality: 0.98 },
            html2canvas: {
                scale: 2,
                useCORS: true,
                backgroundColor: '#ffffff',
                logging: false,
            },
            jsPDF: {
                unit: 'mm',
                format: 'a4',
                orientation: 'portrait',
                compress: true,
            }
        })
        .from(clone)
        .save();

    document.body.removeChild(clone);
}
