import { createContext, useContext, useState } from 'react';

const translations = {
    ID: {
        // Nav
        nav_home: 'Beranda',
        nav_cashbook: 'Catatan Bisnis',
        nav_clients: 'Klien',
        nav_invoice: 'Invoice',
        nav_receipt: 'Kwitansi',
        nav_delivery: 'Tanda Terima',
        nav_quote: 'Penawaran Harga',
        nav_po: 'Purchase Order',
        nav_hpp: 'Hitung HPP',
        nav_report: 'Laporan',
        nav_piutang: 'Hutang & Piutang',
        nav_help: 'Bantuan',
        // Common
        save: 'Simpan',
        cancel: 'Batal',
        delete: 'Hapus',
        edit: 'Edit',
        search: 'Cari...',
        add: 'Tambah',
        saved: 'Tersimpan',
        loading: 'Memuat...',
        no_data: 'Belum ada data',
        back: 'Kembali',
        close: 'Tutup',
        confirm: 'Konfirmasi',
        view_all: 'Lihat Semua',
        upgrade: 'Upgrade Sekarang',
        // Kasir Navigation
        nav_kasir: 'Kasir',
        nav_kasir_pos: '🖥️ Transaksi POS',
        nav_kasir_products: '📦 Manajemen Produk',
        nav_kasir_stock: '📊 Stok & Inventaris',
        nav_kasir_report: '📈 Laporan Kasir',
        nav_kasir_employees: '👥 Karyawan & Shift',
        nav_kasir_customers: '🤝 Klien / Pelanggan',
        nav_kasir_expenses: '💸 Pengeluaran',
        nav_kasir_upgrade: 'Upgrade ke ULTIMATE untuk akses penuh',
        kasir_cart: 'Keranjang',
        kasir_search: 'Cari produk...',
        kasir_products: 'Produk',
        kasir_settings: 'Pengaturan Kasir',
        kasir_no_products: 'Tidak ada produk ditemukan.',
        kasir_save_bill: 'Simpan Open Bill',
        kasir_open_bills: 'Open Bills',
        kasir_back: 'Kembali ke Kasir',
        kasir_report_title: 'Laporan Penjualan',
        kasir_report_desc: 'Pantau performa bisnis dan penjualan kasir Anda.',
        kasir_revenue: 'Pendapatan',
        kasir_transactions: 'Transaksi',
        kasir_discount: 'Diskon',
        kasir_chart: 'Grafik Penjualan',
        kasir_payment_methods: 'Metode Pembayaran',
        kasir_top_products: 'Top 5 Produk Terlaris',
        kasir_no_sales: 'Belum ada data penjualan.',
        kasir_filter_today: 'Hari Ini',
        kasir_filter_week: '7 Hari',
        kasir_filter_month: 'Bulan Ini',
        kasir_products_title: 'Manajemen Produk',
        kasir_products_desc: 'Kelola data stok, harga, dan varian produk kasir Anda.',
        kasir_add_product: 'Tambah Produk',
        kasir_search_name: 'Cari nama produk...',
        kasir_no_products_desc: 'Anda belum menambahkan produk apa pun atau tidak ada yang cocok dengan pencarian.',
        kasir_add_now: 'Tambah sekarang',
        kasir_stock_label: 'Stok',
        kasir_stock_title: 'Stok & Inventaris',
        kasir_stock_desc: 'Pantau ketersediaan barang dan catat riwayat stok masuk.',
        kasir_add_stock: 'Tambah Stok',
        kasir_stock_low: 'Alert Stok Rendah',
        kasir_stock_history: 'Riwayat Stok Masuk',
        kasir_all_products: 'Semua Produk',
        kasir_stock_safe: 'Semua stok aman!',
        kasir_expense_title: 'Pengeluaran Kasir',
        kasir_expense_desc: 'Catat pengeluaran toko yang otomatis tersinkronisasi ke Buku Kas Global.',
        kasir_add_expense: 'Catat Pengeluaran',
        kasir_total_expense: 'Total Pengeluaran',
        kasir_expense_history: 'Riwayat Pengeluaran',
        kasir_employee_title: 'Karyawan & Shift',
        kasir_employee_desc: 'Kelola data staf dan peran akses aplikasi POS.',
        kasir_add_employee: 'Tambah Karyawan',
        kasir_employee_list: 'Daftar Karyawan',
        kasir_no_employees: 'Belum ada data karyawan.',
        // Kasir Components
        kasir_cart_empty: 'Keranjang masih kosong',
        kasir_clear_cart: 'Kosongkan',
        kasir_customer_name_placeholder: 'Nama Pelanggan (Opsional)...',
        kasir_subtotal: 'Subtotal',
        kasir_total: 'TOTAL',
        kasir_save: 'SIMPAN',
        kasir_pay: 'BAYAR',
        kasir_payment_title: 'Pembayaran',
        kasir_total_bill: 'Total Tagihan',
        kasir_payment_method: 'Metode Pembayaran',
        kasir_cash: 'Tunai',
        kasir_transfer: 'Transfer',
        kasir_qris: 'QRIS',
        kasir_amount_received: 'Uang Diterima',
        kasir_change: 'Kembalian',
        kasir_payment_confirm_msg: 'Konfirmasi jika pembayaran sudah diterima/sukses.',
        kasir_cancel: 'Batalkan',
        kasir_confirm: 'Konfirmasi',
        kasir_receipt_title: 'Struk Pembayaran',
        kasir_receipt_no: 'No:',
        kasir_receipt_date: 'Tgl:',
        kasir_receipt_time: 'Jam:',
        kasir_receipt_kasir: 'Kasir:',
        kasir_receipt_client: 'Plg:',
        kasir_thanks: 'Terima kasih!',
        kasir_print_receipt: 'Cetak Struk',
        kasir_close: 'Tutup',
        reset_form: 'Reset Form',
        // Dashboard
        dash_welcome: 'Selamat datang kembali! Ini adalah ringkasan bisnis Anda.',
        dash_income: 'Total Pemasukan Bulan Ini',
        dash_expense: 'Total Pengeluaran Bulan Ini',
        dash_profit: 'Laba Bersih Bulan Ini',
        dash_unpaid: 'Invoice Belum Dibayar',
        dash_quick_income: 'Catat Pemasukan',
        dash_quick_expense: 'Catat Pengeluaran',
        dash_quick_invoice: 'Buat Invoice',
        dash_quick_report: 'Lihat Laporan',
        dash_recent: 'Aktivitas Terbaru',
        dash_chart: 'Grafik 6 Bulan Terakhir',
        dash_unpaid_list: 'Invoice Belum Dibayar',
        dash_no_activity: 'Belum ada aktivitas',
        dash_no_activity_desc: 'Aktivitas bisnis Anda akan muncul di sini',
        dash_no_unpaid: 'Tidak ada invoice tertunggak',
        dash_no_unpaid_desc: 'Semua invoice sudah dibayar',
        dash_kasir_sales: 'Total Penjualan Kasir Hari Ini',
        dash_kasir_tx: 'Total Transaksi Hari Ini',
        dash_legend_invoice: 'Invoice & Lainnya',
        dash_legend_kasir: 'Pendapatan Kasir',
        dash_legend_expense: 'Pengeluaran',
        dash_unpaid_badge: 'Belum Bayar',
        dash_pos_sale: 'Penjualan POS',
        dash_piutang: 'Piutang',
        dash_hutang: 'Hutang',
        dash_active_bills: 'tagihan aktif',
        // Catatan Bisnis
        cb_income: 'Pemasukan',
        cb_expense: 'Pengeluaran',
        cb_balance: 'Saldo Bersih',
        cb_amount: 'Nominal',
        cb_category: 'Kategori',
        cb_note: 'Keterangan',
        cb_date: 'Tanggal',
        cb_filter_today: 'Hari Ini',
        cb_filter_week: 'Minggu',
        cb_filter_month: 'Bulan',
        cb_filter_all: 'Semua',
        cb_daily_total: 'Total Hari Ini',
        cb_limit: 'transaksi hari ini. Upgrade PRO untuk unlimited.',
        // Klien
        kl_title: 'Database Klien',
        kl_add: '+ Tambah Klien',
        kl_detail: 'Lihat Detail',
        kl_total_tr: 'Total Transaksi',
        kl_total_doc: 'Jumlah Dokumen',
        kl_limit: 'Batas gratis 3 klien.',
        // Invoice
        inv_company: 'Informasi Perusahaan',
        inv_client: 'Informasi Klien',
        inv_detail: 'Detail Invoice',
        inv_items: 'Item',
        inv_payment: 'Informasi Pembayaran',
        inv_notes: 'Catatan',
        inv_preview: 'Preview Invoice',
        inv_download: 'Download PDF',
        inv_reset: 'Reset Form',
        inv_mark_paid: 'Tandai Lunas',
        inv_paid_toast: 'Invoice lunas! Kwitansi dibuat.',
        inv_status_unpaid: 'Belum Bayar',
        inv_status_paid: 'Lunas',
        inv_status_waiting: 'Menunggu',
        inv_status_cancelled: 'Dibatalkan',
        // Laporan
        lap_title: 'Laporan Keuangan',
        lap_period: 'Periode',
        lap_export: 'Export Excel',
        lap_total_income: 'Total Pemasukan',
        lap_total_expense: 'Total Pengeluaran',
        lap_net_profit: 'Laba Bersih',
        lap_no_data: 'Tidak ada data untuk periode ini',
        // Kasir
        kasir_tx_limit: 'Batas 10 transaksi gratis/hari tercapai',
        kasir_upgrade_msg: 'Upgrade ULTIMATE untuk transaksi tak terbatas',
        kasir_free_remaining: 'sisa transaksi hari ini',
        // Settings
        set_title: 'Pengaturan',
        set_company: 'Profil Perusahaan',
        set_doc_format: 'Format Nomor Dokumen',
        set_save: 'Simpan Semua',
        set_reset: 'Reset Default',
        set_saved: 'Pengaturan disimpan!',
        // Upgrade
        up_title: 'Batas Penggunaan Tercapai',
        up_cta: 'Upgrade PRO - Rp 99.000/bulan',
        up_ultimate_cta: 'Upgrade ULTIMATE - Rp 149.000/bulan',
        // Footer
        footer: '© 2026 MyInvoice.space',
        // Navbar
        navbar_login: 'Masuk',
        navbar_register: 'Daftar',
        navbar_profile: 'Profil & Pengaturan',
        navbar_upgrade_plan: 'Upgrade Plan',
        navbar_logout: 'Logout',
        navbar_trial_days: 'hari',
        // GlobalSearch
        search_placeholder: 'Cari dokumen, klien, transaksi...',
        search_type_hint: 'Ketik untuk mulai mencari...',
        search_no_results: 'Tidak ada hasil ditemukan',
        search_section_docs: 'Dokumen',
        search_section_clients: 'Klien',
        search_section_tx: 'Transaksi',
        search_close_hint: 'Tutup',
        search_open_hint: 'Buka',
        // Kasir delete confirm
        kasir_delete_bill_title: 'Hapus bill ini?',
        kasir_delete_bill_desc: 'Bill yang dihapus tidak dapat dikembalikan.',
        kasir_open_bills_hint: 'bill tersimpan — klik Load untuk lanjutkan',
        kasir_bill_saved: 'Bill tersimpan!',
        kasir_bill_loaded: 'Bill dimuat ke keranjang!',
        // Sidebar
        sidebar_upgrade_cta: 'Upgrade ke PRO',
        sidebar_upgrade_desc: 'Unlimited dokumen, laporan, & tanpa watermark',
        nav_settings: 'Pengaturan',
        // CatatanBisnis Form
        cb_select_category: '-- Pilih Kategori --',
        cb_note_placeholder: 'Keterangan (opsional)',
        cb_upload_receipt: 'Upload Bukti (opsional)',
        cb_change_receipt: 'Ganti Bukti',
        cb_upload_btn: 'Upload Bukti',
        cb_loading: 'Memuat buku kas...',
        cb_empty_title: 'Belum ada transaksi',
        cb_empty_desc: 'Tambahkan transaksi pertama Anda',
        cb_delete_title: 'Hapus transaksi ini?',
        cb_delete_desc: 'Transaksi akan dihapus permanen dan tidak dapat dikembalikan.',
        cb_limit_banner: 'Transaksi Bulan Ini',
        cb_type_all: 'Semua',
        cb_toast_load_fail: 'Gagal memuat data buku kas',
        cb_toast_limit: 'Limit 20 pencatatan bulanan tercapai. Upgrade ke PRO untuk pencatatan tanpa batas.',
        cb_toast_required: 'Nominal dan kategori wajib diisi',
        cb_toast_save_fail: 'Gagal menyimpan transaksi ke server',
        cb_toast_deleted: 'Transaksi dihapus',
        cb_toast_delete_fail: 'Gagal menghapus transaksi',
        // Kasir Lock Screen
        kasir_monthly_limit_title: 'Limit Transaksi Bulanan Tercapai',
        kasir_monthly_limit_desc: 'Anda telah mencapai batas 50 transaksi gratis per bulan. Upgrade ke PRO untuk transaksi tidak terbatas.',
        kasir_limit_reset: 'Limit reset otomatis setiap awal bulan.',
        kasir_store_name: 'Nama Toko',
        kasir_cashier_name: 'Nama Kasir',
        kasir_logo_url: 'URL Logo Toko (opsional)',
        kasir_tx_left_of: 'dari 50 transaksi gratis sisa bulan ini.',
        kasir_tx_used_up: 'Batas transaksi bulanan tercapai. Reset awal bulan depan.',
        // HitungHPP
        hpp_title: 'Kalkulator HPP Advanced',
        hpp_subtitle: 'Hitung HPP produk secara akurat untuk strategi harga',
        hpp_new_product: '+ Produk Baru',
        hpp_product_name: 'Nama Produk',
        hpp_selling_price: 'Harga Jual (Rp)',
        hpp_raw_materials: 'Bahan Baku',
        hpp_staff_wages: 'Gaji Karyawan',
        hpp_rent_utils: 'Sewa & Utilitas',
        hpp_utilities: 'Utilitas',
        hpp_misc: 'Biaya Lain-lain',
        hpp_platform: 'Biaya Platform',
        hpp_marketplace_fee: 'Biaya Admin Marketplace (%)',
        hpp_marketplace_fee_hint: 'Shopee, Tokopedia, dll.',
        hpp_product_tax: 'Pajak Produk / PPN (%)',
        hpp_product_tax_hint: 'Penyesuaian pajak %',
        hpp_platform_fixed: 'Biaya Platform Tetap (nominal)',
        hpp_platform_fixed_hint: 'Biaya tetap per transaksi',
        hpp_platform_pct: 'Biaya Platform Lainnya (%)',
        hpp_platform_pct_hint: 'Persentase tambahan dari HPP dasar',
        hpp_summary: 'Ringkasan HPP',
        hpp_total_hpp: 'Total HPP Akhir/unit',
        hpp_margin: 'Margin',
        hpp_recommendation: 'Rekomendasi Harga',
        hpp_custom_price: 'Simulasi Harga Custom',
        hpp_minimum: 'Minimum (30%)',
        hpp_ideal: 'Ideal (50%)',
        hpp_premium: 'Premium (100%)',
        hpp_add_item: 'Tambah Item',
        hpp_material_name: 'Nama Bahan',
        hpp_buy_qty: 'Qty Beli',
        hpp_buy_unit: 'Satuan Beli',
        hpp_buy_price: 'Harga Beli (Rp)',
        hpp_use_qty: 'Qty Pakai',
        hpp_use_unit: 'Satuan Pakai',
        hpp_cost_per_unit: 'Biaya/unit',
        hpp_wage_name: 'Nama/Jabatan',
        hpp_wage_type: 'Tipe Gaji',
        hpp_monthly: 'Bulanan',
        hpp_daily: 'Harian',
        hpp_hourly: 'Per Jam',
        hpp_salary: 'Gaji (Rp)',
        hpp_meal_allowance: 'Uang Makan/hari',
        hpp_work_days: 'Hari Kerja/bulan',
        hpp_production_per_day: 'Produksi/hari (unit)',
        hpp_rent_name: 'Nama Sewa',
        hpp_rent_type: 'Periode',
        hpp_annual: 'Tahunan',
        hpp_rent_amount: 'Nominal (Rp)',
        hpp_op_days: 'Hari Operasional/bulan',
        hpp_utility_name: 'Nama Utilitas',
        hpp_monthly_amount: 'Biaya/bulan (Rp)',
        hpp_misc_name: 'Keterangan',
        hpp_amount_per_unit: 'Biaya/unit (Rp)',
        hpp_save_pdf: 'Export PDF',
        hpp_save_product: 'Simpan Produk',
        hpp_no_products: 'Belum ada produk. Klik "+ Produk Baru" untuk mulai.',
        hpp_reset_form: 'Reset Form',
        hpp_upgrade_title: 'Kalkulator HPP Advanced — Fitur ULTIMATE',
        hpp_upgrade_desc: 'Hitung HPP lengkap: bahan baku, gaji karyawan, sewa, utilitas dan lain-lain. Rekomendasi harga otomatis.',
        hpp_upgrade_unlock: 'Upgrade ke ULTIMATE untuk mengakses fitur ini.',
        hpp_upgrade_btn: 'Upgrade ke ULTIMATE',
        hpp_pdf_component: 'Komponen',
        hpp_pdf_cost_unit: 'Biaya/unit',
        hpp_pdf_total: 'TOTAL HPP AKHIR',
        hpp_pdf_rec_title: 'Rekomendasi Harga Jual',
        hpp_pdf_mat_detail: 'Rincian Bahan Baku',
        hpp_pdf_wage_detail: 'Rincian Gaji Karyawan',
        hpp_pdf_rent_detail: 'Rincian Sewa',
        hpp_pdf_util_detail: 'Rincian Utilitas',
        hpp_pdf_misc_detail: 'Rincian Biaya Lain-lain',
        hpp_pdf_mat_name: 'Nama Bahan',
        hpp_pdf_purchase: 'Pembelian',
        hpp_pdf_usage: 'Pemakaian',
        hpp_pdf_total_cost: 'Total Biaya',
        hpp_pdf_position: 'Posisi/Nama',
        hpp_pdf_type_nominal: 'Tipe/Nominal',
        hpp_pdf_production: 'Produksi',
        hpp_pdf_rent_name: 'Nama Sewa',
        hpp_pdf_period_nominal: 'Periode/Nominal',
        hpp_pdf_util_name: 'Nama Utilitas',
        hpp_pdf_monthly_cost: 'Biaya/Bulan',
        hpp_pdf_description: 'Keterangan',
        hpp_unit_per_day: 'unit/hari',
        hpp_toast_download_limit: 'Batas download tercapai. Upgrade PRO!',
    },
    EN: {
        // Nav
        nav_home: 'Home',
        nav_cashbook: 'Business Notes',
        nav_clients: 'Clients',
        nav_invoice: 'Invoice',
        nav_receipt: 'Receipt',
        nav_delivery: 'Delivery Note',
        nav_quote: 'Price Quote',
        nav_po: 'Purchase Order',
        nav_hpp: 'Cost Calculator',
        nav_report: 'Reports',
        nav_piutang: 'Accounts Receivable',
        nav_help: 'Help Center',
        // Common
        save: 'Save',
        cancel: 'Cancel',
        delete: 'Delete',
        edit: 'Edit',
        search: 'Search...',
        add: 'Add',
        saved: 'Saved',
        loading: 'Loading...',
        no_data: 'No data yet',
        back: 'Back',
        close: 'Close',
        confirm: 'Confirm',
        view_all: 'View All',
        upgrade: 'Upgrade Now',
        // Dashboard
        dash_welcome: 'Welcome back! Here is your business summary.',
        dash_income: 'Total Income This Month',
        dash_expense: 'Total Expenses This Month',
        dash_profit: 'Net Profit This Month',
        dash_unpaid: 'Unpaid Invoices',
        dash_quick_income: 'Record Income',
        dash_quick_expense: 'Record Expense',
        dash_quick_invoice: 'Create Invoice',
        dash_quick_report: 'View Reports',
        dash_recent: 'Recent Activity',
        dash_chart: 'Last 6 Months Chart',
        dash_unpaid_list: 'Unpaid Invoices',
        dash_no_activity: 'No activity yet',
        dash_no_activity_desc: 'Your business activity will appear here',
        dash_no_unpaid: 'No overdue invoices',
        dash_no_unpaid_desc: 'All invoices have been paid',
        dash_kasir_sales: "Today's Total POS Sales",
        dash_kasir_tx: "Today's Total Transactions",
        dash_legend_invoice: 'Invoice & Others',
        dash_legend_kasir: 'POS Revenue',
        dash_legend_expense: 'Expenses',
        dash_unpaid_badge: 'Unpaid',
        dash_pos_sale: 'POS Sale',
        dash_piutang: 'Receivables',
        dash_hutang: 'Payables',
        dash_active_bills: 'active bills',
        // Kasir Navigation
        nav_kasir: 'Cashier',
        nav_kasir_pos: '🖥️ POS Transaction',
        nav_kasir_products: '📦 Product Management',
        nav_kasir_stock: '📊 Stock & Inventory',
        nav_kasir_report: '📈 POS Reports',
        nav_kasir_employees: '👥 Staff & Shifts',
        nav_kasir_customers: '🤝 Clients / Customers',
        nav_kasir_expenses: '💸 Expenses',
        nav_kasir_upgrade: 'Upgrade to ULTIMATE for full access',
        nav_kasir_free_label: 'tx remaining',
        kasir_cart: 'Cart',
        kasir_search: 'Search products...',
        kasir_products: 'Products',
        kasir_settings: 'Cashier Settings',
        kasir_no_products: 'No products found.',
        kasir_save_bill: 'Save Open Bill',
        kasir_open_bills: 'Open Bills',
        kasir_back: 'Back to Cashier',
        kasir_report_title: 'Sales Report',
        kasir_report_desc: 'Monitor your business performance and cashier sales.',
        kasir_revenue: 'Revenue',
        kasir_transactions: 'Transactions',
        kasir_discount: 'Discount',
        kasir_chart: 'Sales Chart',
        kasir_payment_methods: 'Payment Methods',
        kasir_top_products: 'Top 5 Best Selling Products',
        kasir_no_sales: 'No sales data yet.',
        kasir_filter_today: 'Today',
        kasir_filter_week: '7 Days',
        kasir_filter_month: 'This Month',
        kasir_products_title: 'Product Management',
        kasir_products_desc: 'Manage stock data, prices, and your cashier product variants.',
        kasir_add_product: 'Add Product',
        kasir_search_name: 'Search product name...',
        kasir_no_products_desc: 'You haven\'t added any products yet or none match your search.',
        kasir_add_now: 'Add now',
        kasir_stock_label: 'Stock',
        kasir_stock_title: 'Stock & Inventory',
        kasir_stock_desc: 'Monitor item availability and record stock entry history.',
        kasir_add_stock: 'Add Stock',
        kasir_stock_low: 'Low Stock Alert',
        kasir_stock_history: 'Stock Entry History',
        kasir_all_products: 'All Products',
        kasir_stock_safe: 'All stock safe!',
        kasir_expense_title: 'Cashier Expenses',
        kasir_expense_desc: 'Record store expenses that are automatically synchronized to the Global Cashbook.',
        kasir_add_expense: 'Record Expense',
        kasir_total_expense: 'Total Expenses',
        kasir_expense_history: 'Expense History',
        kasir_employee_title: 'Employees & Shifts',
        kasir_employee_desc: 'Manage staff data and POS application access roles.',
        kasir_add_employee: 'Add Employee',
        kasir_employee_list: 'Employee List',
        kasir_no_employees: 'No employee data yet.',
        // Kasir Components
        kasir_cart_empty: 'Cart is empty',
        kasir_clear_cart: 'Clear',
        kasir_customer_name_placeholder: 'Customer Name (Optional)...',
        kasir_subtotal: 'Subtotal',
        kasir_total: 'TOTAL',
        kasir_save: 'SAVE',
        kasir_pay: 'PAY',
        kasir_payment_title: 'Payment',
        kasir_total_bill: 'Total Bill',
        kasir_payment_method: 'Payment Method',
        kasir_cash: 'Cash',
        kasir_transfer: 'Transfer',
        kasir_qris: 'QRIS',
        kasir_amount_received: 'Amount Received',
        kasir_change: 'Change',
        kasir_payment_confirm_msg: 'Confirm once payment is received/successful.',
        kasir_cancel: 'Cancel',
        kasir_confirm: 'Confirm',
        kasir_receipt_title: 'Payment Receipt',
        kasir_receipt_no: 'No:',
        kasir_receipt_date: 'Date:',
        kasir_receipt_time: 'Time:',
        kasir_receipt_kasir: 'Cashier:',
        kasir_receipt_client: 'Cust:',
        kasir_thanks: 'Thank you!',
        kasir_print_receipt: 'Print Receipt',
        kasir_close: 'Close',
        reset_form: 'Reset Form',
        // Catatan Bisnis
        cb_income: 'Income',
        cb_expense: 'Expense',
        cb_balance: 'Net Balance',
        cb_amount: 'Amount',
        cb_category: 'Category',
        cb_note: 'Notes',
        cb_date: 'Date',
        cb_filter_today: 'Today',
        cb_filter_week: 'Week',
        cb_filter_month: 'Month',
        cb_filter_all: 'All',
        cb_daily_total: "Today's Total",
        cb_limit: 'transactions today. Upgrade PRO for unlimited.',
        // Klien
        kl_title: 'Client Database',
        kl_add: '+ Add Client',
        kl_detail: 'View Detail',
        kl_total_tr: 'Total Transactions',
        kl_total_doc: 'Document Count',
        kl_limit: 'Free plan: max 3 clients.',
        // Invoice
        inv_company: 'Company Information',
        inv_client: 'Client Information',
        inv_detail: 'Invoice Details',
        inv_items: 'Items',
        inv_payment: 'Payment Information',
        inv_notes: 'Notes',
        inv_preview: 'Invoice Preview',
        inv_download: 'Download PDF',
        inv_reset: 'Reset Form',
        inv_mark_paid: 'Mark as Paid',
        inv_paid_toast: 'Invoice paid! Receipt created.',
        inv_status_unpaid: 'Unpaid',
        inv_status_paid: 'Paid',
        inv_status_waiting: 'Pending',
        inv_status_cancelled: 'Cancelled',
        // Laporan
        lap_title: 'Financial Report',
        lap_period: 'Period',
        lap_export: 'Export Excel',
        lap_total_income: 'Total Income',
        lap_total_expense: 'Total Expenses',
        lap_net_profit: 'Net Profit',
        lap_no_data: 'No data for this period',
        // Kasir
        kasir_tx_limit: 'Daily limit of 10 free transactions reached',
        kasir_upgrade_msg: 'Upgrade to ULTIMATE for unlimited transactions',
        kasir_free_remaining: 'transactions remaining today',
        // Settings
        set_title: 'Settings',
        set_company: 'Company Profile',
        set_doc_format: 'Document Number Format',
        set_save: 'Save All',
        set_reset: 'Reset Default',
        set_saved: 'Settings saved!',
        // Upgrade
        up_title: 'Usage Limit Reached',
        up_cta: 'Upgrade PRO - Rp 99,000/month',
        up_ultimate_cta: 'Upgrade ULTIMATE - Rp 149,000/month',
        // Footer
        footer: '© 2026 MyInvoice.space',
        // Navbar
        navbar_login: 'Sign In',
        navbar_register: 'Register',
        navbar_profile: 'Profile & Settings',
        navbar_upgrade_plan: 'Upgrade Plan',
        navbar_logout: 'Logout',
        navbar_trial_days: 'days',
        // GlobalSearch
        search_placeholder: 'Search documents, clients, transactions...',
        search_type_hint: 'Type to start searching...',
        search_no_results: 'No results found',
        search_section_docs: 'Documents',
        search_section_clients: 'Clients',
        search_section_tx: 'Transactions',
        search_close_hint: 'Close',
        search_open_hint: 'Open',
        // Kasir delete confirm
        kasir_delete_bill_title: 'Delete this bill?',
        kasir_delete_bill_desc: 'Deleted bills cannot be recovered.',
        kasir_open_bills_hint: 'bills saved — tap Load to resume',
        kasir_bill_saved: 'Bill saved!',
        kasir_bill_loaded: 'Bill loaded to cart!',
        // Sidebar
        sidebar_upgrade_cta: 'Upgrade to PRO',
        sidebar_upgrade_desc: 'Unlimited documents, reports & no watermark',
        nav_settings: 'Settings',
        // CatatanBisnis Form
        cb_select_category: '-- Select Category --',
        cb_note_placeholder: 'Notes (optional)',
        cb_upload_receipt: 'Upload Receipt (optional)',
        cb_change_receipt: 'Change Receipt',
        cb_upload_btn: 'Upload Receipt',
        cb_loading: 'Loading cashbook...',
        cb_empty_title: 'No transactions yet',
        cb_empty_desc: 'Add your first transaction',
        cb_delete_title: 'Delete this transaction?',
        cb_delete_desc: 'This transaction will be permanently deleted and cannot be recovered.',
        cb_limit_banner: 'Transactions This Month',
        cb_type_all: 'All',
        cb_toast_load_fail: 'Failed to load cashbook data',
        cb_toast_limit: 'Monthly limit of 20 entries reached. Upgrade to PRO for unlimited entries.',
        cb_toast_required: 'Amount and category are required',
        cb_toast_save_fail: 'Failed to save transaction to server',
        cb_toast_deleted: 'Transaction deleted',
        cb_toast_delete_fail: 'Failed to delete transaction',
        // Kasir Lock Screen
        kasir_monthly_limit_title: 'Monthly Transaction Limit Reached',
        kasir_monthly_limit_desc: 'You have reached the 50 free transactions per month limit. Upgrade to PRO for unlimited transactions.',
        kasir_limit_reset: 'Limit resets automatically at the start of each month.',
        kasir_store_name: 'Store Name',
        kasir_cashier_name: 'Cashier Name',
        kasir_logo_url: 'Store Logo URL (optional)',
        kasir_tx_left_of: 'of 50 free transactions remaining this month.',
        kasir_tx_used_up: 'Monthly transaction limit reached. Resets next month.',
        // HitungHPP
        hpp_title: 'Advanced HPP Calculator',
        hpp_subtitle: 'Accurate product cost calculation for pricing strategy',
        hpp_new_product: '+ New Product',
        hpp_product_name: 'Product Name',
        hpp_selling_price: 'Selling Price (Rp)',
        hpp_raw_materials: 'Raw Materials',
        hpp_staff_wages: 'Staff Wages',
        hpp_rent_utils: 'Rent & Utilities',
        hpp_utilities: 'Utilities',
        hpp_misc: 'Other Costs',
        hpp_platform: 'Platform Costs',
        hpp_marketplace_fee: 'Marketplace Fee (%)',
        hpp_marketplace_fee_hint: 'Shopee, Tokopedia, etc.',
        hpp_product_tax: 'Product Tax / PPN (%)',
        hpp_product_tax_hint: 'Tax adjustment %',
        hpp_platform_fixed: 'Other Fixed Fee (amount)',
        hpp_platform_fixed_hint: 'Fixed fee per transaction (Rp or $)',
        hpp_platform_pct: 'Other Platform Fee (%)',
        hpp_platform_pct_hint: 'Additional percentage of base HPP',
        hpp_summary: 'HPP Summary',
        hpp_total_hpp: 'Total HPP/unit',
        hpp_margin: 'Margin',
        hpp_recommendation: 'Price Recommendation',
        hpp_custom_price: 'Simulate Custom Price',
        hpp_minimum: 'Minimum (30%)',
        hpp_ideal: 'Ideal (50%)',
        hpp_premium: 'Premium (100%)',
        hpp_add_item: 'Add Item',
        hpp_material_name: 'Material Name',
        hpp_buy_qty: 'Buy Qty',
        hpp_buy_unit: 'Buy Unit',
        hpp_buy_price: 'Buy Price (Rp)',
        hpp_use_qty: 'Use Qty',
        hpp_use_unit: 'Use Unit',
        hpp_cost_per_unit: 'Cost/unit',
        hpp_wage_name: 'Position/Name',
        hpp_wage_type: 'Pay Type',
        hpp_monthly: 'Monthly',
        hpp_daily: 'Daily',
        hpp_hourly: 'Hourly',
        hpp_salary: 'Salary (Rp)',
        hpp_meal_allowance: 'Meal Allowance/day',
        hpp_work_days: 'Work Days/month',
        hpp_production_per_day: 'Production/day (units)',
        hpp_rent_name: 'Rent Name',
        hpp_rent_type: 'Period',
        hpp_annual: 'Annual',
        hpp_rent_amount: 'Amount (Rp)',
        hpp_op_days: 'Operational Days/month',
        hpp_utility_name: 'Utility Name',
        hpp_monthly_amount: 'Monthly Cost (Rp)',
        hpp_misc_name: 'Description',
        hpp_amount_per_unit: 'Cost/unit (Rp)',
        hpp_save_pdf: 'Export PDF',
        hpp_save_product: 'Save Product',
        hpp_no_products: 'No products yet. Click "+ New Product" to start.',
        hpp_reset_form: 'Reset Form',
        hpp_upgrade_title: 'Advanced HPP Calculator — ULTIMATE Feature',
        hpp_upgrade_desc: 'Calculate cost of goods with raw materials, staff wages, rent, utilities and more. Auto price recommendations.',
        hpp_upgrade_unlock: 'Upgrade to ULTIMATE to unlock.',
        hpp_upgrade_btn: 'Upgrade to ULTIMATE',
        hpp_pdf_component: 'Component',
        hpp_pdf_cost_unit: 'Cost/unit',
        hpp_pdf_total: 'TOTAL FINAL HPP',
        hpp_pdf_rec_title: 'Selling Price Recommendations',
        hpp_pdf_mat_detail: 'Raw Materials Detail',
        hpp_pdf_wage_detail: 'Staff Wages Detail',
        hpp_pdf_rent_detail: 'Rent Detail',
        hpp_pdf_util_detail: 'Utilities Detail',
        hpp_pdf_misc_detail: 'Other Costs Detail',
        hpp_pdf_mat_name: 'Material Name',
        hpp_pdf_purchase: 'Purchase',
        hpp_pdf_usage: 'Usage',
        hpp_pdf_total_cost: 'Total Cost',
        hpp_pdf_position: 'Position/Name',
        hpp_pdf_type_nominal: 'Type/Amount',
        hpp_pdf_production: 'Production',
        hpp_pdf_rent_name: 'Rent Name',
        hpp_pdf_period_nominal: 'Period/Amount',
        hpp_pdf_util_name: 'Utility Name',
        hpp_pdf_monthly_cost: 'Monthly Cost',
        hpp_pdf_description: 'Description',
        hpp_unit_per_day: 'units/day',
        hpp_toast_download_limit: 'Download limit reached. Upgrade PRO!',
    }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'ID');

    const toggleLang = () => {
        const next = lang === 'ID' ? 'EN' : 'ID';
        setLang(next);
        localStorage.setItem('lang', next);
    };

    const t = (key) => translations[lang][key] || translations['ID'][key] || key;

    return (
        <LanguageContext.Provider value={{ lang, toggleLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLang() {
    return useContext(LanguageContext);
}
