import { createContext, useContext, useState } from 'react';

const translations = {
    ID: {
        // Nav
        nav_home: 'Beranda',
        nav_cashbook: 'Catatan Bisnis',
        nav_clients: 'Klien',
        nav_invoice: 'Invoice',
        nav_receipt: 'Kwitansi',
        nav_delivery: 'Tanda Terima',
        nav_quote: 'Penawaran Harga',
        nav_po: 'Purchase Order',
        nav_hpp: 'Hitung HPP',
        nav_report: 'Laporan',
        nav_piutang: 'Hutang & Piutang',
        nav_help: 'Bantuan',
        // Common
        save: 'Simpan',
        cancel: 'Batal',
        delete: 'Hapus',
        edit: 'Edit',
        search: 'Cari...',
        add: 'Tambah',
        saved: 'Tersimpan',
        loading: 'Memuat...',
        no_data: 'Belum ada data',
        back: 'Kembali',
        close: 'Tutup',
        confirm: 'Konfirmasi',
        view_all: 'Lihat Semua',
        upgrade: 'Upgrade Sekarang',
        // Kasir Navigation
        nav_kasir: 'Kasir',
        nav_kasir_pos: 'Transaksi POS',
        nav_kasir_products: 'Manajemen Produk',
        nav_kasir_stock: 'Stok & Inventaris',
        nav_kasir_report: 'Laporan Kasir',
        nav_kasir_members: 'Member / Anggota',
        nav_kasir_employees: 'Karyawan & Shift',
        nav_kasir_customers: 'Klien / Pelanggan',
        nav_kasir_expenses: 'Pengeluaran',
        nav_kasir_upgrade: 'Upgrade ke ULTIMATE untuk akses penuh',
        kasir_cart: 'Keranjang',
        kasir_search: 'Cari produk...',
        kasir_products: 'Produk',
        kasir_settings: 'Pengaturan Kasir',
        kasir_no_products: 'Tidak ada produk ditemukan.',
        kasir_save_bill: 'Simpan Open Bill',
        kasir_open_bills: 'Open Bills',
        kasir_back: 'Kembali ke Kasir',
        kasir_report_title: 'Laporan Penjualan',
        kasir_report_desc: 'Pantau performa bisnis dan penjualan kasir Anda.',
        kasir_revenue: 'Pendapatan',
        kasir_transactions: 'Transaksi',
        kasir_discount: 'Diskon',
        kasir_chart: 'Grafik Penjualan',
        kasir_payment_methods: 'Metode Pembayaran',
        kasir_top_products: 'Top 5 Produk Terlaris',
        kasir_no_sales: 'Belum ada data penjualan.',
        kasir_filter_today: 'Hari Ini',
        kasir_filter_week: '7 Hari',
        kasir_filter_month: 'Bulan Ini',

        // POS WA Rekap
        share_rekap_wa: 'Rekap ke WA',
        rekap_daily: 'Rekap Harian',
        rekap_transactions: 'Total Transaksi',
        rekap_revenue: 'Total Omzet',
        rekap_avg: 'Rata-rata/Transaksi',
        rekap_top_products: 'Top 3 Produk',
        rekap_payment: 'Metode Pembayaran',
        rekap_low_stock: 'Stok Hampir Habis',

        // Loyalty Member
        member_found: 'Member ditemukan',
        member_not_found: 'Nomor tidak terdaftar sebagai member',
        register_as_member: 'Daftar sebagai member',
        member_points: 'poin',
        member_redeem: 'Tukar Poin',
        member_earn: 'Poin Didapat',
        members_title: 'Daftar Member',
        enable_loyalty: 'Aktifkan Program Loyalty',
        points_per_amount: 'Rp per 1 Poin',
        points_value: 'Nilai 1 Poin (Rp)',

        kasir_products_title: 'Manajemen Produk',
        kasir_products_desc: 'Kelola data stok, harga, dan varian produk kasir Anda.',
        kasir_add_product: 'Tambah Produk',
        kasir_search_name: 'Cari nama produk...',
        kasir_no_products_desc: 'Anda belum menambahkan produk apa pun atau tidak ada yang cocok dengan pencarian.',
        kasir_add_now: 'Tambah sekarang',
        kasir_stock_label: 'Stok',
        kasir_stock_title: 'Stok & Inventaris',
        kasir_stock_desc: 'Pantau ketersediaan barang dan catat riwayat stok masuk.',
        kasir_add_stock: 'Tambah Stok',
        kasir_stock_low: 'Alert Stok Rendah',
        kasir_stock_history: 'Riwayat Stok Masuk',
        kasir_all_products: 'Semua Produk',
        kasir_stock_safe: 'Semua stok aman!',
        kasir_expense_title: 'Pengeluaran Kasir',
        kasir_expense_desc: 'Catat pengeluaran toko yang otomatis tersinkronisasi ke Buku Kas Global.',
        kasir_add_expense: 'Catat Pengeluaran',
        kasir_total_expense: 'Total Pengeluaran',
        kasir_expense_history: 'Riwayat Pengeluaran',
        kasir_employee_title: 'Karyawan & Shift',
        kasir_employee_desc: 'Kelola data staf dan peran akses aplikasi POS.',
        kasir_add_employee: 'Tambah Karyawan',
        kasir_employee_list: 'Daftar Karyawan',
        kasir_no_employees: 'Belum ada data karyawan.',
        // Kasir Components
        kasir_cart_empty: 'Keranjang masih kosong',
        kasir_clear_cart: 'Kosongkan',
        kasir_customer_name_placeholder: 'Nama Pelanggan (Opsional)...',
        kasir_subtotal: 'Subtotal',
        kasir_total: 'TOTAL',
        kasir_save: 'SIMPAN',
        kasir_pay: 'BAYAR',
        kasir_payment_title: 'Pembayaran',
        kasir_total_bill: 'Total Tagihan',
        kasir_payment_method: 'Metode Pembayaran',
        kasir_cash: 'Tunai',
        kasir_transfer: 'Transfer',
        kasir_qris: 'QRIS',
        kasir_amount_received: 'Uang Diterima',
        kasir_change: 'Kembalian',
        kasir_payment_confirm_msg: 'Konfirmasi jika pembayaran sudah diterima/sukses.',
        kasir_cancel: 'Batalkan',
        kasir_confirm: 'Konfirmasi',
        kasir_receipt_title: 'Struk Pembayaran',
        kasir_receipt_no: 'No:',
        kasir_receipt_date: 'Tgl:',
        kasir_receipt_time: 'Jam:',
        kasir_receipt_kasir: 'Kasir:',
        kasir_receipt_client: 'Plg:',
        kasir_thanks: 'Terima kasih!',
        kasir_print_receipt: 'Cetak Struk',
        kasir_close: 'Tutup',
        reset_form: 'Reset Form',
        // Upgrade
        upgrade_title: 'Pilih Plan yang Tepat',
        upgrade_subtitle: 'Mulai gratis, upgrade kapanpun saat bisnis Anda berkembang.',
        upgrade_monthly: 'Bulanan',
        upgrade_yearly: 'Tahunan',
        upgrade_save_20: 'Hemat 20%',
        upgrade_popular: 'POPULER',
        upgrade_choose_plan: 'Pilih Plan Ini',
        upgrade_current_plan: 'Plan Aktif',
        upgrade_trial_left: 'Hari',
        upgrade_code_title: 'Punya Kode Aktivasi?',
        upgrade_code_desc: 'Masukkan kode aktivasi PRO yang Anda terima setelah pembayaran.',
        upgrade_code_placeholder: 'Contoh: MYINVOICE-PRO-XXXX',
        upgrade_activate_btn: 'Aktifkan PRO',
        upgrade_success: 'Akun PRO Aktif! Nikmati semua fitur tanpa batas.',
        upgrade_contact: 'Untuk info pembelian, hubungi kami di',
        // Profile Extra
        profile_delete_confirm_placeholder: 'HAPUS',
        profile_delete_confirm_text: 'HAPUS',
        // PDF Extra
        pdf_payment_info: 'Informasi Pembayaran',
        pdf_bank: 'Bank',
        pdf_account_no: 'No. Rekening',
        pdf_account_name: 'Atas Nama',
        pdf_notes: 'Catatan',
        // Dashboard
        dash_welcome: 'Selamat datang kembali! Ini adalah ringkasan bisnis Anda.',
        dash_income: 'Total Pemasukan Bulan Ini',
        dash_expense: 'Total Pengeluaran Bulan Ini',
        dash_profit: 'Laba Bersih Bulan Ini',
        dash_unpaid: 'Invoice Belum Dibayar',
        dash_quick_income: 'Catat Pemasukan',
        dash_quick_expense: 'Catat Pengeluaran',
        dash_quick_invoice: 'Buat Invoice',
        dash_quick_report: 'Lihat Laporan',
        dash_recent: 'Aktivitas Terbaru',
        dash_chart: 'Grafik 6 Bulan Terakhir',
        dash_unpaid_list: 'Invoice Belum Dibayar',
        dash_no_activity: 'Belum ada aktivitas',
        dash_no_activity_desc: 'Aktivitas bisnis Anda akan muncul di sini',
        dash_no_unpaid: 'Tidak ada invoice tertunggak',
        dash_no_unpaid_desc: 'Semua invoice sudah dibayar',
        dash_kasir_sales: 'Total Penjualan Kasir Hari Ini',
        dash_kasir_tx: 'Total Transaksi Hari Ini',
        dash_legend_invoice: 'Invoice & Lainnya',
        dash_legend_kasir: 'Pendapatan Kasir',
        dash_legend_expense: 'Pengeluaran',
        dash_unpaid_badge: 'Belum Bayar',
        dash_pos_sale: 'Penjualan POS',
        dash_piutang: 'Piutang',
        dash_hutang: 'Hutang',
        dash_active_bills: 'tagihan aktif',
        // Catatan Bisnis
        cb_income: 'Pemasukan',
        cb_expense: 'Pengeluaran',
        cb_balance: 'Saldo Bersih',
        cb_amount: 'Nominal',
        cb_category: 'Kategori',
        cb_note: 'Keterangan',
        cb_date: 'Tanggal',
        cb_filter_today: 'Hari Ini',
        cb_filter_week: 'Minggu',
        cb_filter_month: 'Bulan',
        cb_filter_all: 'Semua',
        cb_daily_total: 'Total Hari Ini',
        cb_limit: 'transaksi hari ini. Upgrade PRO untuk unlimited.',
        // Klien
        kl_title: 'Database Klien',
        kl_add: '+ Tambah Klien',
        kl_detail: 'Lihat Detail',
        kl_total_tr: 'Total Transaksi',
        kl_total_doc: 'Jumlah Dokumen',
        kl_limit: 'Batas gratis 3 klien.',
        // Invoice
        inv_download: 'Download PDF',
        inv_reset: 'Reset Form',
        inv_mark_paid: 'Tandai Lunas',
        inv_paid_toast: 'Invoice lunas! Kwitansi dibuat.',
        inv_status_unpaid: 'Belum Bayar',
        inv_status_paid: 'Lunas',
        inv_status_waiting: 'Menunggu',
        inv_status_cancelled: 'Dibatalkan',
        // Laporan
        lap_title: 'Laporan Keuangan',
        lap_period: 'Periode',
        lap_export: 'Export Excel',
        lap_total_income: 'Total Pemasukan',
        lap_total_expense: 'Total Pengeluaran',
        lap_net_profit: 'Laba Bersih',
        lap_no_data: 'Tidak ada data untuk periode ini',
        // Kasir
        kasir_tx_limit: 'Batas 10 transaksi gratis/hari tercapai',
        kasir_upgrade_msg: 'Upgrade ULTIMATE untuk transaksi tak terbatas',
        kasir_free_remaining: 'sisa transaksi hari ini',
        // Settings
        set_title: 'Pengaturan',
        set_company: 'Profil Perusahaan',
        set_doc_format: 'Format Nomor Dokumen',
        set_save: 'Simpan Semua',
        set_reset: 'Reset Default',
        set_saved: 'Pengaturan disimpan!',
        // Kustomisasi Struk
        receipt_customization: 'Kustomisasi Struk (ULTIMATE)',
        store_name_label: 'Nama Toko',
        store_address_label: 'Alamat Toko',
        store_phone_label: 'Nomor Telepon',
        store_footer_label: 'Pesan Footer',
        store_logo_label: 'Logo Toko',
        store_name_placeholder: 'Nama toko kamu',
        store_footer_placeholder: 'Terima kasih telah berbelanja!',
        receipt_customization_desc: 'Kustomisasi tampilan struk kasir kamu',
        // Upgrade
        up_title: 'Batas Penggunaan Tercapai',
        up_cta: 'Upgrade PRO - Rp 129.000/bulan',
        up_ultimate_cta: 'Upgrade ULTIMATE - Rp 149.000/bulan',
        // Footer
        footer: '© 2026 MyInvoice.space',
        // Navbar
        navbar_login: 'Masuk',
        navbar_register: 'Daftar',
        navbar_profile: 'Profil & Pengaturan',
        navbar_upgrade_plan: 'Upgrade Plan',
        navbar_logout: 'Logout',
        navbar_trial_days: 'hari',
        // GlobalSearch
        search_placeholder: 'Cari dokumen, klien, transaksi...',
        search_type_hint: 'Ketik untuk mulai mencari...',
        search_no_results: 'Tidak ada hasil ditemukan',
        search_section_docs: 'Dokumen',
        search_section_clients: 'Klien',
        search_section_tx: 'Transaksi',
        search_close_hint: 'Tutup',
        search_open_hint: 'Buka',
        // Kasir delete confirm
        kasir_delete_bill_title: 'Hapus bill ini?',
        kasir_delete_bill_desc: 'Bill yang dihapus tidak dapat dikembalikan.',
        kasir_open_bills_hint: 'bill tersimpan — klik Load untuk lanjutkan',
        kasir_bill_saved: 'Bill tersimpan!',
        kasir_bill_loaded: 'Bill dimuat ke keranjang!',
        kasir_select_item: 'Pilih produk dari menu kiri atau scan barcode',
        kasir_badge_free: 'FREE • {used}/50 BULANAN',
        kasir_limit_msg: '{remaining} dari 50 transaksi gratis sisa bulan ini.',

        // PIN & Shift
        pin_enter: 'Masukkan PIN',
        pin_select_employee: 'Pilih Karyawan',
        pin_wrong: 'PIN salah, coba lagi',
        pin_login_btn: 'Masuk',
        shift_started: 'Shift mulai:',
        shift_end: 'Akhiri Shift',
        shift_end_confirm: 'Yakin ingin mengakhiri shift?',
        shift_summary: 'Ringkasan Shift',
        shift_total_trx: 'Total Transaksi',
        shift_total_revenue: 'Total Omzet',
        no_employees_msg: 'Tambah karyawan dulu di menu Karyawan & Shift',

        // Sidebar
        sidebar_upgrade_cta: 'Upgrade ke PRO',
        sidebar_upgrade_desc: 'Unlimited dokumen, laporan, & tanpa watermark',
        nav_settings: 'Pengaturan',
        // CatatanBisnis Form
        cb_select_category: '-- Pilih Kategori --',
        cb_note_placeholder: 'Keterangan (opsional)',
        cb_upload_receipt: 'Upload Bukti (opsional)',
        cb_change_receipt: 'Ganti Bukti',
        cb_upload_btn: 'Upload Bukti',
        cb_loading: 'Memuat buku kas...',
        cb_empty_title: 'Belum ada transaksi',
        cb_empty_desc: 'Tambahkan transaksi pertama Anda',
        cb_delete_title: 'Hapus transaksi ini?',
        cb_delete_desc: 'Transaksi akan dihapus permanen dan tidak dapat dikembalikan.',
        cb_limit_banner: 'Transaksi Bulan Ini',
        cb_type_all: 'Semua',
        cb_toast_load_fail: 'Gagal memuat data buku kas',
        cb_toast_limit: 'Limit 20 pencatatan bulanan tercapai. Upgrade ke PRO untuk pencatatan tanpa batas.',
        cb_toast_required: 'Nominal dan kategori wajib diisi',
        cb_toast_save_fail: 'Gagal menyimpan transaksi ke server',
        cb_toast_deleted: 'Transaksi dihapus',
        cb_toast_delete_fail: 'Gagal menghapus transaksi',
        // Kasir Lock Screen
        kasir_monthly_limit_title: 'Limit Transaksi Bulanan Tercapai',
        kasir_monthly_limit_desc: 'Anda telah mencapai batas 50 transaksi gratis per bulan. Upgrade ke PRO untuk transaksi tidak terbatas.',
        kasir_limit_reset: 'Limit reset otomatis setiap awal bulan.',
        kasir_store_name: 'Nama Toko',
        kasir_cashier_name: 'Nama Kasir',
        kasir_logo_url: 'URL Logo Toko (opsional)',
        kasir_tx_left_of: 'dari 50 transaksi gratis sisa bulan ini.',
        kasir_tx_used_up: 'Batas transaksi bulanan tercapai. Reset awal bulan depan.',
        // Laporan
        laporan_title: 'Laporan',
        laporan_income: 'Pemasukan',
        laporan_expense: 'Pengeluaran',
        laporan_net: 'Laba Bersih',
        laporan_tx_count: 'Jumlah Transaksi',
        laporan_click_detail: 'Klik untuk detail →',
        laporan_income_by_cat: 'Pemasukan per Kategori',
        laporan_expense_by_cat: 'Pengeluaran per Kategori',
        laporan_no_income: 'Tidak ada data pemasukan bulan ini',
        laporan_no_expense: 'Tidak ada data pengeluaran bulan ini',
        laporan_inv_summary: 'Ringkasan Status Invoice',
        laporan_unpaid: 'Belum Bayar',
        laporan_paid: 'Lunas',
        laporan_waiting: 'Menunggu',
        laporan_total: 'Total',
        laporan_no_data: 'Tidak ada data',
        laporan_items_found: 'item ditemukan',
        laporan_click_edit: 'Klik untuk buka & edit →',
        laporan_excel_pro: 'Fitur Export Excel hanya untuk pengguna PRO.',
        // Klien EmptyState
        klien_empty_title: 'Belum ada klien',
        klien_empty_desc: 'Tambahkan klien pertama Anda untuk mulai',
        klien_add_btn: 'Tambah Klien',
        // Karyawan table headers & modal
        kar_col_name: 'Nama Karyawan',
        kar_col_role: 'Peran',
        kar_col_pin: 'PIN Akses',
        kar_col_action: 'Aksi',
        kar_no_pin: 'Tidak Ada',
        kar_modal_add: 'Tambah Karyawan',
        kar_modal_edit: 'Edit Karyawan',
        kar_field_fullname: 'Nama Lengkap',
        kar_field_role: 'Peran / Role',
        kar_field_pin: 'PIN Akses (Opsional, 4-6 digit)',
        kar_pin_banner_title: 'Fitur PIN & Manajemen Shift (Akan Datang)',
        kar_pin_banner_desc: 'Untuk saat ini PIN belum diaktifkan saat login layar sentuh aplikasi POS. Fitur proteksi PIN dan absensi shift sedang dalam pengembangan tahap selanjutnya.',
        kar_toast_save_fail: 'Gagal menyimpan data karyawan. Coba lagi.',
        kar_toast_del_fail: 'Gagal menghapus data karyawan.',
        // Shift History
        shift_history_title: 'Riwayat Shift (20 Terakhir)',
        shift_col_employee: 'Karyawan',
        shift_col_start: 'Mulai',
        shift_col_end: 'Selesai',
        shift_col_trx: 'Trx',
        shift_col_revenue: 'Omzet (Rp)',
        shift_no_history: 'Belum ada riwayat shift',
        shift_active: 'Masih aktif',

        // Laporan Kasir
        sales_report_title: 'Laporan Penjualan Kasir',
        sales_report_desc: 'Pantau performa penjualan toko kamu',
        total_revenue: 'Total Omzet',
        total_transactions: 'Total Transaksi',
        avg_per_transaction: 'Rata-rata/Transaksi',
        total_items_sold: 'Produk Terjual',
        daily_revenue_chart: 'Grafik Omzet Harian',
        top_products: 'Produk Terlaris',
        payment_methods: 'Metode Pembayaran',
        peak_hours: 'Jam Tersibuk',
        transaction_detail: 'Detail Transaksi',
        no_transaction_data: 'Belum ada transaksi di periode ini',
        sidebar_sales_report: 'Laporan Kasir',

        // Form & Txs (Prompt 20)
        col_time: 'Waktu',
        col_invoice_no: 'No. Invoice',
        col_cashier: 'Kasir',
        col_items: 'Items',
        col_method: 'Metode',
        col_total: 'Total',
        client_history: 'Riwayat Transaksi',
        client_history_empty: 'Belum ada transaksi dengan klien ini',
        client_total_value: 'Total Nilai Transaksi',
        client_view_history: 'Lihat Riwayat',
        col_document: 'Dokumen',
        col_status: 'Status',
        debt_overdue: 'hutang/piutang sudah melewati jatuh tempo',
        debt_due_soon: 'hutang/piutang jatuh tempo dalam 3 hari',
        debt_status_paid: 'Lunas',
        debt_status_overdue: 'Terlambat',
        debt_status_soon: 'Segera',
        debt_status_normal: 'Normal',

        // Notifikasi Stok
        stock_alert_title: 'Peringatan Stok',
        stock_low_warning: 'produk hampir habis stoknya',
        stock_out_warning: 'produk sudah habis stok',
        stock_see_detail: 'Lihat Detail',
        stock_manage: 'Kelola Produk',
        stock_status_out: 'HABIS',
        stock_status_low: 'Sisa',
        stock_safe: 'Stok Aman',
        stock_alert_empty: 'Semua stok produk aman',

        // Employee Report
        employee_report_title: 'Laporan Performa Karyawan',
        employee_report_desc: 'Pantau performa dan produktivitas tiap kasir',
        active_cashiers: 'Kasir Aktif',
        period_today: 'Hari Ini',
        period_week: 'Minggu Ini',
        period_month: 'Bulan Ini',
        period_custom: 'Kustom',
        col_total_shifts: 'Total Shift',
        col_total_trx: 'Total Transaksi',
        col_total_revenue: 'Total Omzet',
        col_avg_per_shift: 'Rata-rata/Shift',
        col_duration: 'Durasi',
        btn_detail: 'Detail',
        btn_export_csv: 'Export CSV',
        no_shift_data: 'Belum ada data shift untuk periode ini',
        tab_employee_list: 'Daftar Karyawan',
        tab_employee_report: 'Laporan',

        // HitungHPP
        hpp_title: 'Kalkulator HPP Advanced',
        hpp_subtitle: 'Hitung HPP produk secara akurat untuk strategi harga',
        hpp_new_product: '+ Produk Baru',
        hpp_product_name: 'Nama Produk',
        hpp_selling_price: 'Harga Jual (Rp)',
        hpp_raw_materials: 'Bahan Baku',
        hpp_staff_wages: 'Gaji Karyawan',
        hpp_rent_utils: 'Sewa & Utilitas',
        hpp_utilities: 'Utilitas',
        hpp_misc: 'Biaya Lain-lain',
        hpp_platform: 'Biaya Platform',
        hpp_marketplace_fee: 'Biaya Admin Marketplace (%)',
        hpp_marketplace_fee_hint: 'Shopee, Tokopedia, dll.',
        hpp_product_tax: 'Pajak Produk / PPN (%)',
        hpp_product_tax_hint: 'Penyesuaian pajak %',
        hpp_platform_fixed: 'Biaya Platform Tetap (nominal)',
        hpp_platform_fixed_hint: 'Biaya tetap per transaksi',
        hpp_platform_pct: 'Biaya Platform Lainnya (%)',
        hpp_platform_pct_hint: 'Persentase tambahan dari HPP dasar',
        hpp_summary: 'Ringkasan HPP',
        hpp_total_hpp: 'Total HPP Akhir/unit',
        hpp_margin: 'Margin',
        hpp_recommendation: 'Rekomendasi Harga',
        hpp_custom_price: 'Simulasi Harga Custom',
        hpp_minimum: 'Minimum (30%)',
        hpp_ideal: 'Ideal (50%)',
        hpp_premium: 'Premium (100%)',
        hpp_add_item: 'Tambah Item',
        hpp_material_name: 'Nama Bahan',
        hpp_buy_qty: 'Qty Beli',
        hpp_buy_unit: 'Satuan Beli',
        hpp_buy_price: 'Harga Beli (Rp)',
        hpp_use_qty: 'Qty Pakai',
        hpp_use_unit: 'Satuan Pakai',
        hpp_cost_per_unit: 'Biaya/unit',
        hpp_wage_name: 'Nama/Jabatan',
        hpp_wage_type: 'Tipe Gaji',
        hpp_monthly: 'Bulanan',
        hpp_daily: 'Harian',
        hpp_hourly: 'Per Jam',
        hpp_salary: 'Gaji (Rp)',
        hpp_meal_allowance: 'Uang Makan/hari',
        hpp_work_days: 'Hari Kerja/bulan',
        hpp_production_per_day: 'Produksi/hari (unit)',
        hpp_rent_name: 'Nama Sewa',
        hpp_rent_type: 'Periode',
        hpp_annual: 'Tahunan',
        hpp_rent_amount: 'Nominal (Rp)',
        hpp_op_days: 'Hari Operasional/bulan',
        hpp_utility_name: 'Nama Utilitas',
        hpp_monthly_amount: 'Biaya/bulan (Rp)',
        hpp_misc_name: 'Keterangan',
        hpp_amount_per_unit: 'Biaya/unit (Rp)',
        hpp_save_pdf: 'Export PDF',
        hpp_save_product: 'Simpan Produk',
        hpp_no_products: 'Belum ada produk. Klik "+ Produk Baru" untuk mulai.',
        hpp_reset_form: 'Reset Form',
        hpp_saved_products: 'Produk Tersimpan',
        hpp_reset_confirm: 'Reset semua input?',
        hpp_toast_name_required: 'Nama produk wajib diisi',
        hpp_toast_save_failed: 'Gagal menyimpan: ',
        hpp_toast_system_error: 'Terjadi kesalahan sistem saat menyimpan',
        hpp_upgrade_title: 'Kalkulator HPP Advanced — Fitur ULTIMATE',
        hpp_upgrade_desc: 'Hitung HPP lengkap: bahan baku, gaji karyawan, sewa, utilitas dan lain-lain. Rekomendasi harga otomatis.',
        hpp_upgrade_unlock: 'Upgrade ke ULTIMATE untuk mengakses fitur ini.',
        hpp_upgrade_btn: 'Upgrade ke ULTIMATE',
        hpp_pdf_component: 'Komponen',
        hpp_pdf_cost_unit: 'Biaya/unit',
        hpp_pdf_total: 'TOTAL HPP AKHIR',
        hpp_pdf_rec_title: 'Rekomendasi Harga Jual',
        hpp_pdf_mat_detail: 'Rincian Bahan Baku',
        hpp_pdf_wage_detail: 'Rincian Gaji Karyawan',
        hpp_pdf_rent_detail: 'Rincian Sewa',
        hpp_pdf_util_detail: 'Rincian Utilitas',
        hpp_pdf_misc_detail: 'Rincian Biaya Lain-lain',
        hpp_pdf_mat_name: 'Nama Bahan',
        hpp_pdf_purchase: 'Pembelian',
        hpp_pdf_usage: 'Pemakaian',
        hpp_pdf_total_cost: 'Total Biaya',
        hpp_pdf_position: 'Posisi/Nama',
        hpp_pdf_type_nominal: 'Tipe/Nominal',
        hpp_pdf_production: 'Produksi',
        hpp_pdf_rent_name: 'Nama Sewa',
        hpp_pdf_period_nominal: 'Periode/Nominal',
        hpp_pdf_util_name: 'Nama Utilitas',
        hpp_pdf_monthly_cost: 'Biaya/Bulan',
        hpp_pdf_description: 'Keterangan',
        hpp_unit_per_day: 'unit/hari',
        hpp_toast_download_limit: 'Batas download tercapai. Upgrade PRO!',
        // Document Module (shared)
        doc_tab_new: 'Form Baru',
        doc_tab_history: 'Riwayat',
        doc_no_docs: 'Belum ada dokumen tersimpan',
        doc_see: 'Lihat',
        doc_delete: 'Hapus',
        doc_download_pdf: 'Download PDF',
        doc_downloading: 'Mengunduh...',
        doc_reset_toast: 'Form berhasil direset',
        doc_pdf_success: 'PDF berhasil diunduh',
        doc_pdf_fail: 'Gagal mengunduh PDF',
        doc_saved: 'Tersimpan',
        doc_save_history: 'Simpan ke Riwayat',
        doc_deleted: 'Dokumen dihapus',
        doc_delete_permanent: 'Dokumen ini akan dihapus permanen dan tidak dapat dikembalikan.',
        // Invoice specific
        inv_tab_save: 'Simpan ke Riwayat',
        inv_company: 'Informasi Perusahaan',
        inv_company_name: 'Nama Perusahaan',
        inv_address: 'Alamat',
        inv_city: 'Kota',
        inv_phone: 'Telepon',
        inv_email: 'Email',
        inv_website: 'Website',
        inv_client: 'Informasi Klien',
        inv_client_name: 'Nama Klien',
        inv_detail: 'Detail Invoice',
        inv_number: 'Nomor Invoice',
        inv_status: 'Status',
        inv_date: 'Tanggal',
        inv_due_date: 'Jatuh Tempo',
        inv_currency: 'Mata Uang',
        inv_items_title: 'Item / Produk / Layanan',
        inv_item_name: 'Nama item',
        inv_discount: 'Diskon (%)',
        inv_tax: 'Pajak (%)',
        inv_payment: 'Informasi Pembayaran',
        inv_bank: 'Bank',
        inv_account_no: 'No. Rekening',
        inv_account_name: 'Atas Nama',
        inv_payment_instructions: 'Instruksi Pembayaran',
        inv_notes: 'Catatan',
        inv_extra_notes: 'Catatan tambahan untuk klien...',
        inv_preview: 'Preview Invoice',
        inv_badge_unpaid: 'Belum Bayar',
        inv_pdf_to: 'KEPADA',
        inv_pdf_from: 'DARI',
        inv_pdf_date: 'TANGGAL',
        inv_pdf_due_date: 'JATUH TEMPO',
        inv_pdf_desc: 'DESKRIPSI',
        inv_pdf_qty: 'QTY',
        inv_pdf_unit: 'SATUAN',
        inv_pdf_price: 'HARGA',
        inv_pdf_subtotal: 'SUBTOTAL',
        inv_pdf_total: 'TOTAL',
        // Shared form field labels
        form_number_sph: 'Nomor SPH',
        form_number_po: 'Nomor PO',
        form_date: 'Tanggal',
        form_valid_until: 'Berlaku Sampai',
        form_subject: 'Perihal',
        form_to_name: 'Kepada Yth.',
        form_company: 'Perusahaan (Opsional)',
        // Placeholders & generic doc limits
        placeholder_item_name: 'Nama',
        placeholder_spec: 'Spesifikasi',
        limit_reached_msg: 'Kamu telah mencapai batas limit bulan ini. Upgrade untuk akses unlimited.',
        form_from_company: 'Dari Perusahaan',
        form_address: 'Alamat',
        form_logo: 'Logo Perusahaan',
        form_terms: 'Syarat & Ketentuan',
        form_closing: 'Penutup',
        form_signer_name: 'Nama Penanda Tangan',
        form_signer_title: 'Jabatan',
        form_discount: 'Diskon %',
        form_tax: 'Pajak %',
        form_notes: 'Catatan',
        form_delivery_date: 'Tanggal Pengiriman',
        form_company_name: 'Nama Perusahaan',
        form_company_address: 'Alamat Perusahaan',
        form_payment_term: 'Term Pembayaran',
        form_vendor_title: 'Vendor',
        form_delivery_title: 'Pengiriman',
        form_items_title_po: 'Item Pesanan',
        form_col_name: 'Nama',
        form_col_spec: 'Spesifikasi',
        form_signed_by: 'Disetujui oleh,',
        form_with_respect: 'Hormat Kami,',
        // TandaTerima specific
        ttr_title: 'Tanda Terima',
        ttr_from: 'Diserahkan Oleh',
        ttr_to: 'Diterima Oleh',
        ttr_goods_list: 'Daftar Barang',
        ttr_delete_title: 'Hapus Tanda Terima?',
        ttr_delete_body: 'Dokumen ini akan dihapus permanen.',
        ttr_limit: 'Batas bulanan tercapai (5 tanda terima). Upgrade PRO!',
        ttr_updated: 'Tanda Terima diperbarui',
        ttr_saved: 'Tanda Terima tersimpan',
        ttr_sign_from: 'Yang Menyerahkan',
        ttr_sign_to: 'Yang Menerima',
        // PenawaranHarga specific
        sph_title: 'Penawaran Harga',
        sph_to_invoice: 'Jadikan Invoice',
        sph_delete_title: 'Hapus Penawaran?',
        sph_delete_body: 'Dokumen ini akan dihapus permanen.',
        sph_limit: 'Batas bulanan tercapai (5 penawaran). Upgrade PRO!',
        sph_updated: 'Penawaran diperbarui',
        sph_saved: 'Penawaran tersimpan',
        sph_converted: 'Penawaran dikonversi ke Invoice!',
        sph_details: 'Rincian Penawaran',
        pq_closing_default: 'Demikian penawaran ini kami sampaikan. Kami berharap dapat menjalin kerjasama yang saling menguntungkan.',
        table_nama: 'NAMA',
        table_spesifikasi: 'SPESIFIKASI',
        // PurchaseOrder specific
        po_title: 'Purchase Order',
        po_delete_title: 'Hapus PO?',
        po_delete_body: 'Dokumen ini akan dihapus permanen.',
        po_limit: 'Batas bulanan tercapai (5 PO). Upgrade PRO!',
        po_updated: 'PO diperbarui',
        po_saved: 'PO tersimpan',
        po_details: 'Rincian Pesanan',
        // Modal & Form Bilingual Fixes
        update: 'Perbarui',
        form_col_title: 'Jabatan',
        form_col_company: 'Perusahaan',
        form_table_name: 'Nama',
        form_table_spec: 'Spesifikasi',
        form_table_qty: 'Qty',
        form_table_unit: 'Satuan',
        form_table_price: 'Harga',
        form_table_total: 'Total',
        form_table_condition: 'Kondisi',
        form_table_note: 'Keterangan',
        doc_add_item: '+ Tambah Item',
        doc_add_goods: '+ Tambah Barang',
        kl_modal_edit_title: 'Edit Klien',
        kl_modal_add_title: 'Tambah Klien Baru',
        kl_modal_name: 'Nama Klien',
        kl_modal_name_ph: 'Nama lengkap / nama perusahaan',
        kl_modal_contact: 'Kontak Person',
        kl_modal_contact_ph: 'Nama PIC',
        kl_modal_email: 'Email',
        kl_modal_email_ph: 'email@contoh.com',
        kl_modal_phone: 'Telepon',
        kl_modal_phone_ph: '08xx-xxxx-xxxx',
        kl_modal_address: 'Alamat',
        kl_modal_address_ph: 'Jl. ...',
        kl_modal_city: 'Kota',
        kl_modal_city_ph: 'Jakarta',
        kl_modal_notes: 'Catatan',
        kl_modal_notes_ph: 'Catatan tambahan',
        prod_edit_title: 'Edit Produk',
        prod_add_title: 'Tambah Produk Baru',
        prod_name: 'Nama Produk',
        prod_name_ph: 'Misal: Nasi Goreng Spesial',
        prod_price: 'Harga (Rp)',
        prod_stock: 'Stok Awal',
        prod_category: 'Kategori',
        prod_emoji: 'Ikon Emoji',
        prod_del_title: 'Hapus Produk',
        ttr_title_doc: 'TANDA TERIMA BARANG',
        // Bilingual preview keys
        client_limit_info: '{used}/{limit} klien (gratis). Upgrade PRO untuk unlimited klien.',
        dn_doc_title: 'TANDA TERIMA BARANG',
        dn_delivered_by: 'DISERAHKAN OLEH',
        dn_received_by: 'DITERIMA OLEH',
        pq_doc_title: 'SURAT PENAWARAN HARGA',
        pq_to_label: 'KEPADA YTH.',
        pq_valid_until_label: 'Berlaku s/d',
        doc_date_label: 'Tanggal',
        doc_number_label: 'Nomor',
        doc_closing_regards: 'Hormat Kami,',

        btn_try_pro_trial: 'Coba PRO Gratis 14 Hari',
        btn_start_pro: 'Mulai PRO – Rp 129.000/bln',
        btn_start_ultimate: 'Mulai ULTIMATE',

        // Notifikasi Bell
        notif_title: 'Notifikasi',
        notif_empty: 'Tidak ada notifikasi baru',
        notif_debt_due: 'jatuh tempo besok',
        notif_debt_due_days: 'jatuh tempo dalam {n} hari',
        notif_debt_overdue: 'sudah melewati jatuh tempo',
        notif_stock_low: 'hampir habis (sisa {n})',
        notif_stock_out: 'stok habis',

        // POS SKU & Barcode
        sku_label: 'Kode SKU',
        sku_placeholder: 'Kode SKU (opsional)',
        sku_duplicate_error: 'Kode SKU sudah dipakai produk lain',
        search_or_sku: 'Cari produk atau ketik SKU...',
        scan_barcode: 'Scan Barcode',
        barcode_not_found: 'Produk dengan barcode ini tidak ditemukan',
        barcode_added: 'ditambahkan ke cart',
        generate_sku: 'Generate Otomatis',
        aim_camera: 'Arahkan kamera ke barcode produk',

        // POS Share & Discount
        share_wa: 'Kirim via WhatsApp',
        customer_phone: 'No. HP Pelanggan (opsional)',
        discount_label: 'Diskon',
        discount_percent: 'Persen (%)',
        discount_nominal: 'Nominal (Rp)',
        voucher_code: 'Kode Voucher',
        voucher_apply: 'Terapkan',
        voucher_not_found: 'Kode voucher tidak ditemukan',
        voucher_expired: 'Voucher sudah kadaluarsa',
        voucher_max_used: 'Voucher sudah mencapai batas penggunaan',
        voucher_min_purchase: 'Minimum pembelian untuk voucher ini:',
        voucher_applied: 'Voucher berhasil diterapkan!',
        voucher_management: 'Manajemen Voucher',
        voucher_add: 'Tambah Voucher',
        voucher_active: 'Aktif',
        voucher_inactive: 'Nonaktif',

        // Onboarding Wizard
        onboard_title: 'Selamat Datang di My Invoice! 👋',
        onboard_subtitle: 'Mari setup toko Anda dalam 4 langkah mudah',
        onboard_step1: 'Info Toko',
        onboard_step2: 'Jenis Usaha',
        onboard_step3: 'Fitur Utama',
        onboard_step4: 'Selesai',
        onboard_store_name: 'Nama Toko',
        onboard_store_name_placeholder: 'Contoh: Warung Makan Jovan',
        onboard_store_address: 'Alamat Toko (opsional)',
        onboard_store_phone: 'No. Telepon (opsional)',
        onboard_upload_logo: 'Upload Logo (opsional)',
        onboard_business_type: 'Pilih Jenis Usaha',
        onboard_features: 'Fitur apa yang paling sering Anda butuhkan?',
        onboard_next: 'Lanjut',
        onboard_back: 'Kembali',
        onboard_skip: 'Lewati',
        onboard_finish: 'Mulai Gunakan My Invoice →',
        onboard_welcome: 'Toko Anda Sudah Siap! 🎉',
        onboard_summary_type: 'Jenis usaha',
        onboard_summary_features: 'Fitur aktif',

        // FIX-10: KasirMembers hardcoded text
        members_subtitle: 'Kelola pelanggan setia dan poin kasir',
        members_add: 'Tambah Member',
        members_search_ph: 'Cari nama atau nomor WA...',
        members_col_name: 'Nama',
        members_col_phone: 'No. WhatsApp',
        members_col_points: 'Total Poin',
        members_col_spent: 'Total Belanja',
        members_col_action: 'Aksi',
        members_not_found: 'Tidak ada member ditemukan',
        members_edit_title: 'Edit Member',
        members_add_title: 'Tambah Member',
        members_field_name: 'Nama Pelanggan',
        members_field_phone: 'No. WhatsApp',
        members_delete_title: 'Hapus Member?',
        members_delete_desc: 'Data histori poin juga akan terhapus. Aksi ini tidak dapat dibatalkan.',
        members_saving: 'Menyimpan...',
        members_saved_ok: 'Member berhasil ditambahkan',
        members_updated_ok: 'Member berhasil diperbarui',
        members_deleted_ok: 'Member berhasil dihapus',
        members_load_fail: 'Gagal memuat data member',
        members_save_fail: 'Gagal menyimpan member',
        members_delete_fail: 'Gagal menghapus member',
        members_phone_dup: 'No. WhatsApp sudah terdaftar',
        members_required: 'Nama dan No. WhatsApp wajib diisi',

        // FIX-10: PaymentModal hardcoded text
        payment_search_member: 'Cari Member',
        payment_searching: 'Mencari...',
        payment_search_ph: 'Cari nomor HP member...',
        payment_search_btn: 'Cari',
        payment_member_not_found: 'Member tidak ditemukan',
        payment_redeem_label: 'Jumlah Poin Ditukar',
        payment_processing: 'Memproses...',

        // FIX-10: Kasir setup error screen
        kasir_setup_title: 'Sedang Menyiapkan Modul Kasir...',
        kasir_setup_desc: 'Database untuk fitur Kasir belum disiapkan. Pastikan Anda telah menjalankan tabel SQL terbaru untuk Kasir di Supabase.',
        kasir_setup_retry: 'Coba Muat Ulang',

        // FIX-10: LaporanKasir pagination & labels
        laporan_page_of: 'Halaman {current} dari {total}',
        laporan_prev: 'Prev',
        laporan_next: 'Next',
        laporan_sold_qty: 'terjual',

        // Landing Page Overhaul
        landing_nav_products: 'Produk',
        landing_nav_features: 'Fitur',
        landing_nav_pricing: 'Harga',
        landing_nav_faq: 'FAQ',
        landing_nav_contact: 'Kontak',
        landing_nav_login: 'Masuk',
        landing_nav_register: 'Daftar Gratis',
        
        landing_mega_col1: 'Dokumen Bisnis',
        landing_mega_col1_inv: 'Invoice',
        landing_mega_col1_inv_d: 'Buat & kirim invoice profesional',
        landing_mega_col1_kw: 'Kwitansi',
        landing_mega_col1_kw_d: 'Bukti pembayaran resmi',
        landing_mega_col1_tt: 'Tanda Terima',
        landing_mega_col1_tt_d: 'Dokumen tanda terima',
        landing_mega_col1_sph: 'Penawaran Harga',
        landing_mega_col1_sph_d: 'Quote ke klien',
        landing_mega_col1_po: 'Purchase Order',
        landing_mega_col1_po_d: 'PO ke supplier',
        landing_mega_col1_hp: 'Hutang & Piutang',
        landing_mega_col1_hp_d: 'Pantau tagihan',

        landing_mega_col2: 'Kasir & Operasional',
        landing_mega_col2_pos: 'Kasir POS',
        landing_mega_col2_pos_d: 'Sistem kasir digital',
        landing_mega_col2_prod: 'Manajemen Produk',
        landing_mega_col2_prod_d: 'Katalog & stok',
        landing_mega_col2_emp: 'Karyawan & Shift',
        landing_mega_col2_emp_d: 'Manajemen tim kasir',
        landing_mega_col2_scan: 'Barcode Scanner',
        landing_mega_col2_scan_d: 'Scan via kamera HP',
        landing_mega_col2_voc: 'Voucher Promo',
        landing_mega_col2_voc_d: 'Kode diskon pelanggan',
        landing_mega_col2_loy: 'Loyalty & Member',
        landing_mega_col2_loy_d: 'Program poin pelanggan',

        landing_mega_col3: 'Laporan & Analitik',
        landing_mega_col3_fin: 'Laporan Keuangan',
        landing_mega_col3_fin_d: 'Pemasukan & pengeluaran',
        landing_mega_col3_pos: 'Laporan Kasir',
        landing_mega_col3_pos_d: 'Omzet & produk terlaris',
        landing_mega_col3_note: 'Catatan Bisnis',
        landing_mega_col3_note_d: 'Jurnal keuangan manual',
        landing_mega_col3_exp: 'Export PDF & CSV',
        landing_mega_col3_exp_d: 'Download laporan',
        landing_mega_col3_multi: 'Multi Outlet',
        landing_mega_col3_multi_d: 'Kelola banyak cabang',
        landing_mega_col3_white: 'White Label',
        landing_mega_col3_white_d: 'Branding sendiri',

        landing_mega_cta: 'Siap coba semua fitur ini? → Daftar Gratis Sekarang',

        landing_hero_title: 'Kelola bisnis lebih mudah, dibayar lebih cepat.',
        landing_hero_sub: 'Invoice, kasir POS, laporan keuangan, dan loyalty member — semua dalam satu aplikasi. Gratis selamanya untuk memulai.',
        landing_hero_badge: 'BARU: APLIKASI BISNIS ALL-IN-ONE',
        landing_hero_cta1: 'Mulai Gratis Sekarang',
        landing_hero_cta2: 'Lihat Fitur',
        
        landing_stats_users: '5.000+ Pengguna Aktif',
        landing_stats_docs: '20rb+ Dokumen Terkirim',
        landing_stats_uptime: '99.9% Uptime Server',
        landing_stats_satisfaction: '4.9★ Kepuasan Pengguna',

        landing_feat_filter_all: 'Semua',
        landing_feat_filter_free: 'FREE',
        landing_feat_filter_pro: 'PRO',
        landing_feat_filter_ultimate: 'ULTIMATE',

        features_title: 'Semua yang kamu butuhkan',
        features_sub: 'Dari kasir hingga laporan keuangan — sudah termasuk dalam satu aplikasi.',
        pricing_title: 'Mulai gratis, upgrade kapan saja',
        pricing_subtitle: 'Harga transparan. Tidak ada biaya tersembunyi. Batal kapan saja.',

        landing_how_title: 'Cara Kerja',
        landing_how_step1_t: 'Daftar Gratis',
        landing_how_step1_d: 'Konfirmasi email & langsung login.',
        landing_how_step2_t: 'Setup Bisnis',
        landing_how_step2_d: 'Upload logo & isi info bisnis Anda.',
        landing_how_step3_t: 'Tambah Data',
        landing_how_step3_d: 'Masukkan produk & data klien.',
        landing_how_step4_t: 'Mulai Jual',
        landing_how_step4_d: 'Kirim invoice & pantau laporan.',

        landing_pricing_badge_popular: 'Paling Populer',
        landing_pricing_badge_ultimate: 'Terbaik untuk bisnis besar',
        landing_pricing_guarantee: '✓ Tidak ada biaya tersembunyi ✓ Batal kapan saja ✓ Tidak perlu kartu kredit',

        landing_faq_q1: 'Apakah benar-benar gratis selamanya?',
        landing_faq_a1: 'Ya, plan FREE My Invoice benar-benar gratis tanpa batas waktu — bukan trial 30 hari, bukan freemium yang tiba-tiba berbayar. Kamu bisa membuat invoice, mengelola klien, dan menggunakan kasir POS tanpa mengeluarkan sepeser pun. Upgrade ke PRO atau ULTIMATE hanya diperlukan jika bisnis kamu berkembang dan membutuhkan fitur yang lebih canggih seperti laporan mendalam, barcode scanner, atau program loyalitas pelanggan.',
        landing_faq_q2: 'Bagaimana cara upgrade ke PRO atau ULTIMATE?',
        landing_faq_a2: 'Upgrade sangat mudah dan bisa dilakukan kapan saja langsung dari dalam aplikasi. Cukup masuk ke menu Upgrade di sidebar, pilih plan yang sesuai kebutuhan bisnis kamu, lalu selesaikan pembayaran via transfer bank atau QRIS. Plan kamu akan aktif otomatis dalam hitungan menit setelah pembayaran dikonfirmasi — tanpa perlu menghubungi tim kami, tanpa antri, tanpa repot.',
        landing_faq_q3: 'Apakah data saya aman?',
        landing_faq_a3: 'Keamanan data kamu adalah prioritas utama kami. Semua data disimpan di server terenkripsi dengan standar keamanan tingkat enterprise. Kami tidak pernah menjual, membagikan, atau menggunakan data bisnis kamu untuk keperluan apapun selain menjalankan layanan ini. Setiap akun dilindungi dengan autentikasi yang aman, dan seluruh koneksi menggunakan enkripsi SSL/HTTPS. Data kamu adalah milik kamu sepenuhnya.',
        landing_faq_q4: 'Bisa pakai di HP, tablet, dan laptop?',
        landing_faq_a4: 'Tentu saja. My Invoice dirancang sebagai aplikasi berbasis web yang responsif penuh, sehingga bekerja sempurna di semua perangkat — smartphone Android maupun iPhone, tablet, laptop, hingga PC desktop. Tidak perlu install aplikasi apapun. Cukup buka browser, login, dan kamu sudah bisa langsung bekerja dari perangkat manapun, kapanpun, di manapun.',
        landing_faq_q5: 'Apakah ada masa trial untuk PRO/ULTIMATE?',
        landing_faq_a5: 'Ya! Pengguna baru yang mendaftar melalui link promo khusus akan mendapatkan akses trial 14 hari untuk semua fitur PRO dan ULTIMATE secara gratis — tanpa perlu memasukkan data kartu kredit. Ini kesempatan kamu untuk merasakan sendiri bagaimana fitur seperti laporan kasir mendalam, program loyalitas member, dan barcode scanner bisa mengubah cara kamu mengelola bisnis sebelum memutuskan untuk berlangganan.',
        landing_faq_q6: 'Bagaimana jika saya lupa password?',
        landing_faq_a6: 'Tenang, ini mudah diatasi. Di halaman login, klik tombol "Lupa Password", masukkan alamat email yang kamu gunakan saat mendaftar, dan kami akan langsung mengirimkan link reset password ke inbox kamu. Ikuti instruksi di email tersebut, dan kamu bisa membuat password baru dalam kurang dari 2 menit. Jika email tidak masuk, cek folder spam atau hubungi kami via WhatsApp untuk bantuan langsung.',
        landing_faq_q7: 'Apakah invoice bisa dilihat klien tanpa daftar?',
        landing_faq_a7: 'Tidak perlu. Klien kamu bisa menerima invoice dalam format PDF yang dikirim langsung via WhatsApp atau email — tanpa perlu membuat akun My Invoice. PDF invoice tampil profesional dengan logo toko, detail tagihan lengkap, dan informasi pembayaran yang jelas. Fitur link invoice publik yang memungkinkan klien melihat dan membayar langsung via browser saat ini sedang dalam pengembangan dan akan segera tersedia.',
        landing_faq_q8: 'Bagaimana cara menghubungi support?',
        landing_faq_a8: 'Kami siap membantu kamu kapanpun dibutuhkan. Kamu bisa menghubungi kami melalui WhatsApp untuk respons tercepat, atau kirim email ke support@myinvoice.space untuk pertanyaan yang lebih detail. Tim kami beroperasi setiap hari dan berkomitmen untuk memberikan respons dalam waktu kurang dari 24 jam. Kamu juga bisa mengisi form kontak di bagian bawah halaman ini dan kami akan segera menghubungi kamu kembali.',

        testimonials_title: 'Apa kata mereka?',
        landing_testi1_text: 'Dulu ribet catat transaksi manual. Sejak pakai My Invoice, kirim tagihan ke supplier tinggal klik, stok juga terpantau rapi. Sangat membantu UMKM!',
        landing_testi1_name: 'Budi Santoso',
        landing_testi1_role: 'Owner Kopi Kenangan Manis',
        landing_testi2_text: 'Fitur kasir POS-nya enteng banget dibuka di HP. Barcode scanner-nya lancar, bikin antrean jadi lebih cepat. CS-nya juga ramah lewat WA.',
        landing_testi2_name: 'Siti Aminah',
        landing_testi2_role: 'Butik Fashion Muslimah',
        landing_testi3_text: 'Laporan keuangannya lengkap banget. Saya bisa tahu profit per hari tanpa perlu buka laptop. Rekomendasi buat yang mau rapihin admin bisnis.',
        landing_testi3_name: 'Andi Wijaya',
        landing_testi3_role: 'Distributor Alat Tulis',

        landing_contact_title: 'Hubungi Kami',
        landing_contact_sub: 'Punya pertanyaan atau butuh bantuan khusus? Tim kami siap membantu bisnis Anda tumbuh lebih cepat.',
        landing_contact_name: 'Nama',
        landing_contact_email: 'Email',
        landing_contact_message: 'Pesan',
        landing_contact_send: 'Kirim Pesan',
        landing_contact_wa: 'Chat via WhatsApp',

        landing_final_cta: 'Mulai sekarang — gratis selamanya!',
        landing_final_btn: 'Daftar Gratis Sekarang →',
        landing_footer_tagline: 'Kelola bisnis lebih mudah, dibayar lebih cepat.',
        landing_footer_services: 'Layanan',
        landing_footer_company: 'Perusahaan',
        landing_footer_policy: 'Kebijakan Privasi',
        landing_footer_terms: 'Syarat & Ketentuan',
        landing_footer_resources: 'Bantuan',
        landing_footer_blog: 'Artikel & Blog',
        landing_footer_made_with: '© 2026 myinvoice.space • Dibuat dengan ❤️ untuk UMKM Indonesia.',
    },
    EN: {
        // Nav
        nav_home: 'Home',
        nav_cashbook: 'Business Notes',
        nav_clients: 'Clients',
        nav_invoice: 'Invoice',
        nav_receipt: 'Receipt',
        nav_delivery: 'Delivery Note',
        nav_quote: 'Price Quote',
        nav_po: 'Purchase Order',
        nav_hpp: 'Cost Calculator',
        nav_report: 'Reports',
        nav_piutang: 'Accounts Receivable',
        nav_help: 'Help Center',
        // Common
        save: 'Save',
        cancel: 'Cancel',
        delete: 'Delete',
        edit: 'Edit',
        search: 'Search...',
        add: 'Add',
        saved: 'Saved',
        loading: 'Loading...',
        no_data: 'No data yet',
        back: 'Back',
        close: 'Close',
        confirm: 'Confirm',
        view_all: 'View All',
        upgrade: 'Upgrade Now',
        // Kustomisasi Struk
        receipt_customization: 'Receipt Customization (ULTIMATE)',
        store_name_label: 'Store Name',
        store_address_label: 'Store Address',
        store_phone_label: 'Phone Number',
        store_footer_label: 'Footer Message',
        store_logo_label: 'Store Logo',
        store_name_placeholder: 'Your store name',
        store_footer_placeholder: 'Thank you for shopping with us!',
        receipt_customization_desc: 'Customize your cashier receipt appearance',
        // Dashboard
        dash_welcome: 'Welcome back! Here is your business summary.',
        dash_income: 'Total Income This Month',
        dash_expense: 'Total Expenses This Month',
        dash_profit: 'Net Profit This Month',
        dash_unpaid: 'Unpaid Invoices',
        dash_quick_income: 'Record Income',
        dash_quick_expense: 'Record Expense',
        dash_quick_invoice: 'Create Invoice',
        dash_quick_report: 'View Reports',
        dash_recent: 'Recent Activity',
        dash_chart: 'Last 6 Months Chart',
        dash_unpaid_list: 'Unpaid Invoices',
        dash_no_activity: 'No activity yet',
        dash_no_activity_desc: 'Your business activity will appear here',
        dash_no_unpaid: 'No overdue invoices',
        dash_no_unpaid_desc: 'All invoices have been paid',
        dash_kasir_sales: "Today's Total POS Sales",
        dash_kasir_tx: "Today's Total Transactions",
        dash_legend_invoice: 'Invoice & Others',
        dash_legend_kasir: 'POS Revenue',
        dash_legend_expense: 'Expenses',
        dash_unpaid_badge: 'Unpaid',
        dash_pos_sale: 'POS Sale',
        dash_piutang: 'Receivables',
        dash_hutang: 'Payables',
        dash_active_bills: 'active bills',
        // Kasir Navigation
        nav_kasir: 'Cashier',
        nav_kasir_pos: 'POS Transaction',
        nav_kasir_products: 'Product Management',
        nav_kasir_stock: 'Stock & Inventory',
        nav_kasir_report: 'POS Reports',
        nav_kasir_members: 'Members',
        nav_kasir_employees: 'Staff & Shifts',
        nav_kasir_customers: 'Clients / Customers',
        nav_kasir_expenses: 'Expenses',
        nav_kasir_upgrade: 'Upgrade to ULTIMATE for full access',
        nav_kasir_free_label: 'tx remaining',
        kasir_cart: 'Cart',
        kasir_search: 'Search products...',
        kasir_products: 'Products',
        kasir_settings: 'Cashier Settings',
        kasir_no_products: 'No products found.',
        kasir_save_bill: 'Save Open Bill',
        kasir_open_bills: 'Open Bills',
        kasir_back: 'Back to Cashier',
        kasir_report_title: 'Sales Report',
        kasir_report_desc: 'Monitor your business performance and cashier sales.',
        kasir_revenue: 'Revenue',
        kasir_transactions: 'Transactions',
        kasir_discount: 'Discount',
        kasir_chart: 'Sales Chart',
        kasir_payment_methods: 'Payment Methods',
        kasir_top_products: 'Top 5 Best Selling Products',
        kasir_no_sales: 'No sales data yet.',
        kasir_filter_today: 'Today',
        kasir_filter_week: '7 Days',
        kasir_filter_month: 'This Month',

        // POS WA Rekap
        share_rekap_wa: 'Daily Report to WA',
        rekap_daily: 'Daily Summary',
        rekap_transactions: 'Total Transactions',
        rekap_revenue: 'Total Revenue',
        rekap_avg: 'Avg per Transaction',
        rekap_top_products: 'Top 3 Products',
        rekap_payment: 'Payment Methods',
        rekap_low_stock: 'Low Stock Alert',

        // Loyalty Member
        member_found: 'Member found',
        member_not_found: 'Phone not registered as member',
        register_as_member: 'Register as member',
        member_points: 'points',
        member_redeem: 'Redeem Points',
        member_earn: 'Points Earned',
        members_title: 'Member List',
        enable_loyalty: 'Enable Loyalty Program',
        points_per_amount: 'Rp per 1 Point',
        points_value: '1 Point Value (Rp)',

        kasir_products_title: 'Product Management',
        kasir_products_desc: 'Manage stock data, prices, and your cashier product variants.',
        kasir_add_product: 'Add Product',
        kasir_search_name: 'Search product name...',
        kasir_no_products_desc: 'You haven\'t added any products yet or none match your search.',
        kasir_add_now: 'Add now',
        kasir_stock_label: 'Stock',
        kasir_stock_title: 'Stock & Inventory',
        kasir_stock_desc: 'Monitor item availability and record stock entry history.',
        kasir_add_stock: 'Add Stock',
        kasir_stock_low: 'Low Stock Alert',
        kasir_stock_history: 'Stock Entry History',
        kasir_all_products: 'All Products',
        kasir_stock_safe: 'All stock safe!',
        kasir_expense_title: 'Cashier Expenses',
        kasir_expense_desc: 'Record store expenses that are automatically synchronized to the Global Cashbook.',
        kasir_add_expense: 'Record Expense',
        kasir_total_expense: 'Total Expenses',
        kasir_expense_history: 'Expense History',
        kasir_employee_title: 'Employees & Shifts',
        kasir_employee_desc: 'Manage staff data and POS application access roles.',
        kasir_add_employee: 'Add Employee',
        kasir_employee_list: 'Employee List',
        kasir_no_employees: 'No employee data yet.',
        // Laporan
        laporan_title: 'Report',
        laporan_income: 'Income',
        laporan_expense: 'Expenses',
        laporan_net: 'Net Profit',
        laporan_tx_count: 'Transactions',
        laporan_click_detail: 'Click for details →',
        laporan_income_by_cat: 'Income by Category',
        laporan_expense_by_cat: 'Expenses by Category',
        laporan_no_income: 'No income data this month',
        laporan_no_expense: 'No expense data this month',
        laporan_inv_summary: 'Invoice Status Summary',
        laporan_unpaid: 'Unpaid',
        laporan_paid: 'Paid',
        laporan_waiting: 'Pending',
        laporan_total: 'Total',
        laporan_no_data: 'No data',
        laporan_items_found: 'items found',
        laporan_click_edit: 'Click to open & edit →',
        laporan_excel_pro: 'Excel Export is a PRO feature.',
        // Klien EmptyState
        klien_empty_title: 'No clients yet',
        klien_empty_desc: 'Add your first client to get started',
        klien_add_btn: 'Add Client',
        // Karyawan table headers & modal
        kar_col_name: 'Employee Name',
        kar_col_role: 'Role',
        kar_col_pin: 'Access PIN',
        kar_col_action: 'Action',
        kar_no_pin: 'None',
        kar_modal_add: 'Add Employee',
        kar_modal_edit: 'Edit Employee',
        kar_field_fullname: 'Full Name',
        kar_field_role: 'Role',
        kar_field_pin: 'Access PIN (Optional, 4-6 digits)',
        kar_pin_banner_title: 'PIN & Shift Management (Coming Soon)',
        kar_pin_banner_desc: 'PIN login is not yet active on the POS touch screen. PIN protection and shift attendance features are under development.',
        kar_toast_save_fail: 'Failed to save employee. Try again.',
        kar_toast_del_fail: 'Failed to delete employee.',
        // Shift History
        shift_history_title: 'Shift History (Last 20)',
        shift_col_employee: 'Employee',
        shift_col_start: 'Start',
        shift_col_end: 'End',
        shift_col_trx: 'Trx',
        shift_col_revenue: 'Revenue (Rp)',
        shift_no_history: 'No shift history yet',
        shift_active: 'Active',

        // Laporan Kasir
        sales_report_title: 'Sales Report',
        sales_report_desc: 'Monitor your store sales performance',
        total_revenue: 'Total Revenue',
        total_transactions: 'Total Transactions',
        avg_per_transaction: 'Avg per Transaction',
        total_items_sold: 'Items Sold',
        daily_revenue_chart: 'Daily Revenue Chart',
        top_products: 'Top Products',
        payment_methods: 'Payment Methods',
        peak_hours: 'Peak Hours',
        transaction_detail: 'Transaction Details',
        no_transaction_data: 'No transactions for this period',
        sidebar_sales_report: 'Sales Report',

        // Form & Txs (Prompt 20)
        col_time: 'Time',
        col_invoice_no: 'Invoice No.',
        col_cashier: 'Cashier',
        col_items: 'Items',
        col_method: 'Method',
        col_total: 'Total',
        client_history: 'Transaction History',
        client_history_empty: 'No transactions with this client yet',
        client_total_value: 'Total Transaction Value',
        client_view_history: 'View History',
        col_document: 'Document',
        col_status: 'Status',
        debt_overdue: 'debts/receivables are overdue',
        debt_due_soon: 'debts/receivables due within 3 days',
        debt_status_paid: 'Paid',
        debt_status_overdue: 'Overdue',
        debt_status_soon: 'Due Soon',
        debt_status_normal: 'Normal',

        // Notifikasi Stok
        stock_alert_title: 'Stock Warning',
        stock_low_warning: 'products are running low',
        stock_out_warning: 'products are out of stock',
        stock_see_detail: 'See Details',
        stock_manage: 'Manage Products',
        stock_status_out: 'OUT',
        stock_status_low: 'Left',
        stock_safe: 'Stock Safe',
        stock_alert_empty: 'All product stocks are safe',

        // Employee Report
        employee_report_title: 'Employee Performance Report',
        employee_report_desc: 'Monitor the performance and productivity of each cashier',
        active_cashiers: 'Active Cashiers',
        period_today: 'Today',
        period_week: 'This Week',
        period_month: 'This Month',
        period_custom: 'Custom',
        col_total_shifts: 'Total Shifts',
        col_total_trx: 'Total Transactions',
        col_total_revenue: 'Total Revenue',
        col_avg_per_shift: 'Avg per Shift',
        col_duration: 'Duration',
        btn_detail: 'Detail',
        btn_export_csv: 'Export CSV',
        no_shift_data: 'No shift data for this period',
        tab_employee_list: 'Employee List',
        tab_employee_report: 'Report',

        // Kasir Components
        kasir_cart_empty: 'Cart is empty',
        kasir_clear_cart: 'Clear',
        kasir_customer_name_placeholder: 'Customer Name (Optional)...',
        kasir_subtotal: 'Subtotal',
        kasir_total: 'TOTAL',
        kasir_save: 'SAVE',
        kasir_pay: 'PAY',
        kasir_payment_title: 'Payment',
        kasir_total_bill: 'Total Bill',
        kasir_payment_method: 'Payment Method',
        kasir_cash: 'Cash',
        kasir_transfer: 'Transfer',
        kasir_qris: 'QRIS',
        kasir_amount_received: 'Amount Received',
        kasir_change: 'Change',
        kasir_payment_confirm_msg: 'Confirm once payment is received/successful.',
        kasir_cancel: 'Cancel',
        kasir_confirm: 'Confirm',
        kasir_receipt_title: 'Payment Receipt',
        kasir_receipt_no: 'No:',
        kasir_receipt_date: 'Date:',
        kasir_receipt_time: 'Time:',
        kasir_receipt_kasir: 'Cashier:',
        kasir_receipt_client: 'Cust:',
        kasir_thanks: 'Thank you!',
        kasir_print_receipt: 'Print Receipt',
        kasir_close: 'Close',
        reset_form: 'Reset Form',
        // Catatan Bisnis
        cb_income: 'Income',
        cb_expense: 'Expense',
        cb_balance: 'Net Balance',
        cb_amount: 'Amount',
        cb_category: 'Category',
        cb_note: 'Notes',
        cb_date: 'Date',
        cb_filter_today: 'Today',
        cb_filter_week: 'Week',
        cb_filter_month: 'Month',
        cb_filter_all: 'All',
        cb_daily_total: "Today's Total",
        cb_limit: 'transactions today. Upgrade PRO for unlimited.',
        // Klien
        kl_title: 'Client Database',
        kl_add: '+ Add Client',
        kl_detail: 'View Detail',
        kl_total_tr: 'Total Transactions',
        kl_total_doc: 'Document Count',
        kl_limit: 'Free plan: max 3 clients.',
        // Invoice
        inv_download: 'Download PDF',
        inv_reset: 'Reset Form',
        inv_mark_paid: 'Mark as Paid',
        inv_paid_toast: 'Invoice paid! Receipt created.',
        inv_status_unpaid: 'Unpaid',
        inv_status_paid: 'Paid',
        inv_status_waiting: 'Pending',
        inv_status_cancelled: 'Cancelled',
        // Laporan
        lap_title: 'Financial Report',
        lap_period: 'Period',
        lap_export: 'Export Excel',
        lap_total_income: 'Total Income',
        lap_total_expense: 'Total Expenses',
        lap_net_profit: 'Net Profit',
        lap_no_data: 'No data for this period',
        // Kasir
        kasir_tx_limit: 'Daily limit of 10 free transactions reached',
        kasir_upgrade_msg: 'Upgrade to ULTIMATE for unlimited transactions',
        kasir_free_remaining: 'transactions remaining today',

        // PIN & Shift
        pin_enter: 'Enter PIN',
        pin_select_employee: 'Select Employee',
        pin_wrong: 'Wrong PIN, please try again',
        pin_login_btn: 'Login',
        shift_started: 'Shift started:',
        shift_end: 'End Shift',
        shift_end_confirm: 'Are you sure you want to end the shift?',
        shift_summary: 'Shift Summary',
        shift_total_trx: 'Total Transactions',
        shift_total_revenue: 'Total Revenue',
        no_employees_msg: 'Please add employees first in the Employees & Shifts menu',

        // Settings
        set_title: 'Settings',
        set_company: 'Company Profile',
        set_doc_format: 'Document Number Format',
        set_save: 'Save All',
        set_reset: 'Reset Default',
        set_saved: 'Settings saved!',
        // Upgrade
        up_title: 'Usage Limit Reached',
        up_cta: 'Upgrade PRO - Rp 129,000/month',
        up_ultimate_cta: 'Upgrade ULTIMATE - Rp 149,000/month',
        // Footer
        footer: '© 2026 MyInvoice.space',
        // Navbar
        navbar_login: 'Sign In',
        navbar_register: 'Register',
        navbar_profile: 'Profile & Settings',
        navbar_upgrade_plan: 'Upgrade Plan',
        navbar_logout: 'Logout',
        navbar_trial_days: 'days',
        // GlobalSearch
        search_placeholder: 'Search documents, clients, transactions...',
        search_type_hint: 'Type to start searching...',
        search_no_results: 'No results found',
        search_section_docs: 'Documents',
        search_section_clients: 'Clients',
        search_section_tx: 'Transactions',
        search_close_hint: 'Close',
        search_open_hint: 'Open',
        // Kasir delete confirm
        kasir_delete_bill_title: 'Delete this bill?',
        kasir_delete_bill_desc: 'Deleted bills cannot be recovered.',
        kasir_open_bills_hint: 'bills saved — tap Load to resume',
        kasir_bill_saved: 'Bill saved!',
        kasir_bill_loaded: 'Bill loaded to cart!',
        // Sidebar
        sidebar_upgrade_cta: 'Upgrade to PRO',
        sidebar_upgrade_desc: 'Unlimited documents, reports & no watermark',
        nav_settings: 'Settings',
        // CatatanBisnis Form
        cb_select_category: '-- Select Category --',
        cb_note_placeholder: 'Notes (optional)',
        cb_upload_receipt: 'Upload Receipt (optional)',
        cb_change_receipt: 'Change Receipt',
        cb_upload_btn: 'Upload Receipt',
        cb_loading: 'Loading cashbook...',
        cb_empty_title: 'No transactions yet',
        cb_empty_desc: 'Add your first transaction',
        cb_delete_title: 'Delete this transaction?',
        cb_delete_desc: 'This transaction will be permanently deleted and cannot be recovered.',
        cb_limit_banner: 'Transactions This Month',
        cb_type_all: 'All',
        cb_toast_load_fail: 'Failed to load cashbook data',
        cb_toast_limit: 'Monthly limit of 20 entries reached. Upgrade to PRO for unlimited entries.',
        cb_toast_required: 'Amount and category are required',
        cb_toast_save_fail: 'Failed to save transaction to server',
        cb_toast_deleted: 'Transaction deleted',
        cb_toast_delete_fail: 'Failed to delete transaction',
        // Kasir Lock Screen
        kasir_monthly_limit_title: 'Monthly Transaction Limit Reached',
        kasir_monthly_limit_desc: 'You have reached the 50 free transactions per month limit. Upgrade to PRO for unlimited transactions.',
        kasir_limit_reset: 'Limit resets automatically at the start of each month.',
        kasir_store_name: 'Store Name',
        kasir_cashier_name: 'Cashier Name',
        kasir_logo_url: 'Store Logo URL (optional)',
        kasir_tx_left_of: 'of 50 free transactions remaining this month.',
        kasir_tx_used_up: 'Monthly transaction limit reached. Resets next month.',
        // HitungHPP
        hpp_title: 'Advanced HPP Calculator',
        hpp_subtitle: 'Accurate product cost calculation for pricing strategy',
        hpp_new_product: '+ New Product',
        hpp_product_name: 'Product Name',
        hpp_selling_price: 'Selling Price (Rp)',
        hpp_raw_materials: 'Raw Materials',
        hpp_staff_wages: 'Staff Wages',
        hpp_rent_utils: 'Rent & Utilities',
        hpp_utilities: 'Utilities',
        hpp_misc: 'Other Costs',
        hpp_platform: 'Platform Costs',
        hpp_marketplace_fee: 'Marketplace Fee (%)',
        hpp_marketplace_fee_hint: 'Shopee, Tokopedia, etc.',
        hpp_product_tax: 'Product Tax / PPN (%)',
        hpp_product_tax_hint: 'Tax adjustment %',
        hpp_platform_fixed: 'Other Fixed Fee (amount)',
        hpp_platform_fixed_hint: 'Fixed fee per transaction (Rp or $)',
        hpp_platform_pct: 'Other Platform Fee (%)',
        hpp_platform_pct_hint: 'Additional percentage of base HPP',
        hpp_summary: 'HPP Summary',
        hpp_total_hpp: 'Total HPP/unit',
        hpp_margin: 'Margin',
        hpp_recommendation: 'Price Recommendation',
        hpp_custom_price: 'Simulate Custom Price',
        hpp_minimum: 'Minimum (30%)',
        hpp_ideal: 'Ideal (50%)',
        hpp_premium: 'Premium (100%)',
        hpp_add_item: 'Add Item',
        hpp_material_name: 'Material Name',
        hpp_buy_qty: 'Buy Qty',
        hpp_buy_unit: 'Buy Unit',
        hpp_buy_price: 'Buy Price (Rp)',
        hpp_use_qty: 'Use Qty',
        hpp_use_unit: 'Use Unit',
        hpp_cost_per_unit: 'Cost/unit',
        hpp_wage_name: 'Position/Name',
        hpp_wage_type: 'Pay Type',
        hpp_monthly: 'Monthly',
        hpp_daily: 'Daily',
        hpp_hourly: 'Hourly',
        hpp_salary: 'Salary (Rp)',
        hpp_meal_allowance: 'Meal Allowance/day',
        hpp_work_days: 'Work Days/month',
        hpp_production_per_day: 'Production/day (units)',
        hpp_rent_name: 'Rent Name',
        hpp_rent_type: 'Period',
        hpp_annual: 'Annual',
        hpp_rent_amount: 'Amount (Rp)',
        hpp_op_days: 'Operational Days/month',
        hpp_utility_name: 'Utility Name',
        hpp_monthly_amount: 'Monthly Cost (Rp)',
        hpp_misc_name: 'Description',
        hpp_amount_per_unit: 'Cost/unit (Rp)',
        hpp_save_pdf: 'Export PDF',
        hpp_save_product: 'Save Product',
        hpp_no_products: 'No products yet. Click "+ New Product" to start.',
        hpp_reset_form: 'Reset Form',
        hpp_saved_products: 'Saved Products',
        hpp_reset_confirm: 'Reset all fields?',
        hpp_toast_name_required: 'Product name is required',
        hpp_toast_save_failed: 'Save failed: ',
        hpp_toast_system_error: 'System error occurred',
        hpp_upgrade_title: 'Advanced HPP Calculator — ULTIMATE Feature',
        hpp_upgrade_desc: 'Calculate cost of goods with raw materials, staff wages, rent, utilities and more. Auto price recommendations.',
        hpp_upgrade_unlock: 'Upgrade to ULTIMATE to unlock.',
        hpp_upgrade_btn: 'Upgrade to ULTIMATE',
        hpp_pdf_component: 'Component',
        hpp_pdf_cost_unit: 'Cost/unit',
        hpp_pdf_total: 'TOTAL FINAL HPP',
        hpp_pdf_rec_title: 'Selling Price Recommendations',
        hpp_pdf_mat_detail: 'Raw Materials Detail',
        hpp_pdf_wage_detail: 'Staff Wages Detail',
        hpp_pdf_rent_detail: 'Rent Detail',
        hpp_pdf_util_detail: 'Utilities Detail',
        hpp_pdf_misc_detail: 'Other Costs Detail',
        hpp_pdf_mat_name: 'Material Name',
        hpp_pdf_purchase: 'Purchase',
        hpp_pdf_usage: 'Usage',
        hpp_pdf_total_cost: 'Total Cost',
        hpp_pdf_position: 'Position/Name',
        hpp_pdf_type_nominal: 'Type/Amount',
        hpp_pdf_production: 'Production',
        hpp_pdf_rent_name: 'Rent Name',
        hpp_pdf_period_nominal: 'Period/Amount',
        hpp_pdf_util_name: 'Utility Name',
        hpp_pdf_monthly_cost: 'Monthly Cost',
        hpp_pdf_description: 'Description',
        hpp_unit_per_day: 'units/day',
        hpp_toast_download_limit: 'Download limit reached. Upgrade PRO!',
        // Document Module (shared)
        doc_tab_new: 'New Form',
        doc_tab_history: 'History',
        doc_no_docs: 'No saved documents yet',
        doc_see: 'View',
        doc_delete: 'Delete',
        doc_download_pdf: 'Download PDF',
        doc_downloading: 'Downloading...',
        doc_reset_toast: 'Form has been reset',
        doc_pdf_success: 'PDF downloaded successfully',
        doc_pdf_fail: 'Failed to download PDF',
        doc_saved: 'Saved',
        doc_save_history: 'Save to History',
        doc_deleted: 'Document deleted',
        doc_delete_permanent: 'This document will be permanently deleted and cannot be undone.',
        // Invoice specific
        inv_tab_save: 'Save to History',
        inv_company: 'Company Information',
        inv_company_name: 'Company Name',
        inv_address: 'Address',
        inv_city: 'City',
        inv_phone: 'Phone',
        inv_email: 'Email',
        inv_website: 'Website',
        inv_client: 'Client Information',
        inv_client_name: 'Client Name',
        inv_detail: 'Invoice Details',
        inv_number: 'Invoice Number',
        inv_status: 'Status',
        inv_date: 'Date',
        inv_due_date: 'Due Date',
        inv_currency: 'Currency',
        inv_items_title: 'Items / Products / Services',
        inv_item_name: 'Item name',
        inv_discount: 'Discount (%)',
        inv_tax: 'Tax (%)',
        inv_payment: 'Payment Information',
        inv_bank: 'Bank',
        inv_account_no: 'Account No.',
        inv_account_name: 'Account Name',
        inv_payment_instructions: 'Payment Instructions',
        inv_notes: 'Notes',
        inv_extra_notes: 'Additional notes for client...',
        inv_preview: 'Invoice Preview',
        inv_badge_unpaid: 'Unpaid',
        inv_pdf_to: 'TO',
        inv_pdf_from: 'FROM',
        inv_pdf_date: 'DATE',
        inv_pdf_due_date: 'DUE DATE',
        inv_pdf_desc: 'DESCRIPTION',
        inv_pdf_qty: 'QTY',
        inv_pdf_unit: 'UNIT',
        inv_pdf_price: 'PRICE',
        inv_pdf_subtotal: 'SUBTOTAL',
        inv_pdf_total: 'TOTAL',
        // Shared form field labels
        form_number_sph: 'SPH Number',
        form_number_po: 'PO Number',
        form_date: 'Date',
        form_valid_until: 'Valid Until',
        form_subject: 'Subject',
        form_to_name: 'To (Attn.)',
        form_company: 'Company',
        form_from_company: 'From Company',
        form_address: 'Address',
        form_logo: 'Company Logo',
        form_terms: 'Terms & Conditions',
        form_closing: 'Closing',
        form_signer_name: 'Signer Name',
        form_signer_title: 'Title / Position',
        form_discount: 'Discount %',
        form_tax: 'Tax %',
        form_notes: 'Notes',
        form_delivery_date: 'Delivery Date',
        form_company_name: 'Company Name',
        form_company_address: 'Company Address',
        form_payment_term: 'Payment Term',
        form_vendor_title: 'Vendor',
        form_delivery_title: 'Shipping',
        form_items_title_po: 'Order Items',
        form_col_name: 'Name',
        form_col_spec: 'Specification',
        form_signed_by: 'Approved by,',
        form_with_respect: 'Yours sincerely,',
        // TandaTerima specific
        ttr_title: 'Goods Receipt',
        ttr_from: 'Delivered By',
        ttr_to: 'Received By',
        ttr_goods_list: 'Goods List',
        ttr_delete_title: 'Delete Receipt?',
        ttr_delete_body: 'This document will be permanently deleted.',
        ttr_limit: 'Monthly limit reached (5 receipts). Upgrade PRO!',
        ttr_updated: 'Receipt updated',
        ttr_saved: 'Receipt saved',
        ttr_sign_from: 'Delivered By',
        ttr_sign_to: 'Received By',
        // PenawaranHarga specific
        sph_title: 'Price Quotation',
        sph_to_invoice: 'Convert to Invoice',
        sph_delete_title: 'Delete Quotation?',
        sph_delete_body: 'This document will be permanently deleted.',
        sph_limit: 'Monthly limit reached (5 quotations). Upgrade PRO!',
        sph_updated: 'Quotation updated',
        sph_saved: 'Quotation saved',
        sph_converted: 'Quotation converted to Invoice!',
        sph_details: 'Quotation Details',
        pq_closing_default: 'We hereby submit this proposal. We hope to establish a mutually beneficial cooperation.',
        table_nama: 'NAME',
        table_spesifikasi: 'SPECIFICATION',
        // PurchaseOrder specific
        po_title: 'Purchase Order',
        po_delete_title: 'Delete PO?',
        po_delete_body: 'This document will be permanently deleted.',
        po_limit: 'Monthly limit reached (5 POs). Upgrade PRO!',
        po_updated: 'PO updated',
        po_saved: 'PO saved',
        po_details: 'Order Details',
        // Modal & Form Bilingual Fixes
        update: 'Update',
        form_col_title: 'Title',
        form_col_company: 'Company',
        form_table_name: 'Name',
        form_table_spec: 'Specification',
        form_table_qty: 'Qty',
        form_table_unit: 'Unit',
        form_table_price: 'Price',
        form_table_total: 'Total',
        form_table_condition: 'Condition',
        form_table_note: 'Note',
        doc_add_item: '+ Add Item',
        doc_add_goods: '+ Add Goods',
        kl_modal_edit_title: 'Edit Client',
        kl_modal_add_title: 'Add New Client',
        kl_modal_name: 'Client Name',
        kl_modal_name_ph: 'Full name / company name',
        kl_modal_contact: 'Contact Person',
        kl_modal_contact_ph: 'PIC Name',
        kl_modal_email: 'Email',
        kl_modal_email_ph: 'email@example.com',
        kl_modal_phone: 'Phone',
        kl_modal_phone_ph: 'Phone number',
        kl_modal_address: 'Address',
        kl_modal_address_ph: 'Street ...',
        kl_modal_city: 'City',
        kl_modal_city_ph: 'City name',
        kl_modal_notes: 'Notes',
        kl_modal_notes_ph: 'Additional notes',
        prod_edit_title: 'Edit Product',
        prod_add_title: 'Add New Product',
        prod_name: 'Product Name',
        prod_name_ph: 'e.g. Special Fried Rice',
        prod_price: 'Price',
        prod_stock: 'Initial Stock',
        prod_category: 'Category',
        prod_emoji: 'Emoji Icon',
        prod_del_title: 'Delete Product',
        ttr_title_doc: 'DELIVERY NOTE',
        // Bilingual preview keys
        client_limit_info: '{used}/{limit} clients (free). Upgrade to PRO for unlimited clients.',
        dn_doc_title: 'DELIVERY NOTE',
        dn_delivered_by: 'DELIVERED BY',
        dn_received_by: 'RECEIVED BY',
        pq_doc_title: 'PRICE QUOTATION',
        pq_to_label: 'ATTN.',
        pq_valid_until_label: 'Valid until',
        doc_date_label: 'Date',
        doc_number_label: 'Number',
        doc_closing_regards: 'Sincerely,',

        btn_try_pro_trial: 'Try PRO Free 14 Days',
        btn_start_pro: 'Start PRO – Rp 129,000/mo',
        btn_start_ultimate: 'Start ULTIMATE',

        // Notifications Bell
        notif_title: 'Notifications',
        notif_empty: 'No new notifications',
        notif_debt_due: 'due tomorrow',
        notif_debt_due_days: 'due in {n} days',
        notif_debt_overdue: 'is overdue',
        notif_stock_low: 'running low ({n} left)',
        notif_stock_out: 'out of stock',

        // POS SKU & Barcode
        sku_label: 'SKU Code',
        sku_placeholder: 'SKU Code (optional)',
        sku_duplicate_error: 'SKU code already used by another product',
        search_or_sku: 'Search product or type SKU...',
        scan_barcode: 'Scan Barcode',
        barcode_not_found: 'Product with this barcode not found',
        barcode_added: 'added to cart',
        generate_sku: 'Auto Generate',
        aim_camera: 'Aim camera at product barcode',

        // POS Share & Discount
        share_wa: 'Send via WhatsApp',
        customer_phone: 'Customer Phone (optional)',
        discount_label: 'Discount',
        discount_percent: 'Percent (%)',
        discount_nominal: 'Nominal (Rp)',
        voucher_code: 'Voucher Code',
        voucher_apply: 'Apply',
        voucher_not_found: 'Voucher code not found',
        voucher_expired: 'Voucher has expired',
        voucher_max_used: 'Voucher has reached usage limit',
        voucher_min_purchase: 'Minimum purchase for this voucher:',
        voucher_applied: 'Voucher applied successfully!',
        voucher_management: 'Voucher Management',
        voucher_add: 'Add Voucher',
        voucher_active: 'Active',
        voucher_inactive: 'Inactive',

        // Onboarding Wizard
        onboard_title: 'Welcome to My Invoice! 👋',
        onboard_subtitle: 'Let\'s set up your store in 4 easy steps',
        onboard_step1: 'Store Info',
        onboard_step2: 'Business Type',
        onboard_step3: 'Main Features',
        onboard_step4: 'Done',
        onboard_store_name: 'Store Name',
        onboard_store_name_placeholder: 'Example: Jovan\'s Restaurant',
        onboard_store_address: 'Store Address (optional)',
        onboard_store_phone: 'Phone Number (optional)',
        onboard_upload_logo: 'Upload Logo (optional)',
        onboard_business_type: 'Select Business Type',
        onboard_features: 'Which features do you need most?',
        onboard_next: 'Next',
        onboard_back: 'Back',
        onboard_skip: 'Skip',
        onboard_finish: 'Start Using My Invoice →',
        onboard_welcome: 'Your Store is Ready! 🎉',
        onboard_summary_type: 'Business type',
        onboard_summary_features: 'Active features',

        // FIX-10: KasirMembers hardcoded text (EN)
        members_subtitle: 'Manage loyal customers and POS loyalty points',
        members_add: 'Add Member',
        members_search_ph: 'Search name or WhatsApp number...',
        members_col_name: 'Name',
        members_col_phone: 'WhatsApp No.',
        members_col_points: 'Total Points',
        members_col_spent: 'Total Spent',
        members_col_action: 'Action',
        members_not_found: 'No members found',
        members_edit_title: 'Edit Member',
        members_add_title: 'Add Member',
        members_field_name: 'Customer Name',
        members_field_phone: 'WhatsApp No.',
        members_delete_title: 'Delete Member?',
        members_delete_desc: 'Points history will also be deleted. This action cannot be undone.',
        members_saving: 'Saving...',
        members_saved_ok: 'Member added successfully',
        members_updated_ok: 'Member updated successfully',
        members_deleted_ok: 'Member deleted',
        members_load_fail: 'Failed to load members',
        members_save_fail: 'Failed to save member',
        members_delete_fail: 'Failed to delete member',
        members_phone_dup: 'WhatsApp number already registered',
        members_required: 'Name and WhatsApp number are required',

        // FIX-10: PaymentModal hardcoded text (EN)
        payment_search_member: 'Search Member',
        payment_searching: 'Searching...',
        payment_search_ph: 'Search member phone number...',
        payment_search_btn: 'Search',
        payment_member_not_found: 'Member not found',
        payment_redeem_label: 'Points to Redeem',
        payment_processing: 'Processing...',

        // FIX-10: Kasir setup error screen (EN)
        kasir_setup_title: 'Setting Up Kasir Module...',
        kasir_setup_desc: 'Kasir database tables are not ready. Please run the latest Kasir SQL schema in your Supabase SQL Editor.',
        kasir_setup_retry: 'Retry',

        // FIX-10: LaporanKasir pagination & labels (EN)
        laporan_page_of: 'Page {current} of {total}',
        laporan_prev: 'Prev',
        laporan_next: 'Next',
        laporan_sold_qty: 'sold',

        // Landing Page Overhaul (EN)
        landing_nav_products: 'Products',
        landing_nav_features: 'Features',
        landing_nav_pricing: 'Pricing',
        landing_nav_faq: 'FAQ',
        landing_nav_contact: 'Contact',
        landing_nav_login: 'Login',
        landing_nav_register: 'Register Free',
        
        landing_mega_col1: 'Business Documents',
        landing_mega_col1_inv: 'Invoice',
        landing_mega_col1_inv_d: 'Create & send professional invoices',
        landing_mega_col1_kw: 'Receipt',
        landing_mega_col1_kw_d: 'Official payment proof',
        landing_mega_col1_tt: 'Delivery Note',
        landing_mega_col1_tt_d: 'Delivery acknowledgment',
        landing_mega_col1_sph: 'Price Quote',
        landing_mega_col1_sph_d: 'Quotation to clients',
        landing_mega_col1_po: 'Purchase Order',
        landing_mega_col1_po_d: 'PO to suppliers',
        landing_mega_col1_hp: 'Accounts Payable',
        landing_mega_col1_hp_d: 'Track bills & debts',

        landing_mega_col2: 'POS & Operations',
        landing_mega_col2_pos: 'Cashier POS',
        landing_mega_col2_pos_d: 'Digital cashier system',
        landing_mega_col2_prod: 'Product Management',
        landing_mega_col2_prod_d: 'Catalog & stock',
        landing_mega_col2_emp: 'Staff & Shifts',
        landing_mega_col2_emp_d: 'Cashier team management',
        landing_mega_col2_scan: 'Barcode Scanner',
        landing_mega_col2_scan_d: 'Scan via phone camera',
        landing_mega_col2_voc: 'Promo Voucher',
        landing_mega_col2_voc_d: 'Customer discount codes',
        landing_mega_col2_loy: 'Loyalty & Member',
        landing_mega_col2_loy_d: 'Customer points program',

        landing_mega_col3: 'Reports & Analytics',
        landing_mega_col3_fin: 'Financial Reports',
        landing_mega_col3_fin_d: 'Income & expenses',
        landing_mega_col3_pos: 'Cashier Reports',
        landing_mega_col3_pos_d: 'Revenue & top products',
        landing_mega_col3_note: 'Business Notes',
        landing_mega_col3_note_d: 'Manual financial journal',
        landing_mega_col3_exp: 'Export PDF & CSV',
        landing_mega_col3_exp_d: 'Download reports',
        landing_mega_col3_multi: 'Multi Outlet',
        landing_mega_col3_multi_d: 'Manage multiple branches',
        landing_mega_col3_white: 'White Label',
        landing_mega_col3_white_d: 'Your own branding',

        landing_mega_cta: 'Ready to try all features? → Register Free Now',

        landing_hero_title: 'Manage business easier, get paid faster.',
        landing_hero_sub: 'Invoice, POS, financial reports, and loyalty members — all in one app. Free forever to start.',
        landing_hero_badge: 'NEW: ALL-IN-ONE BUSINESS APP',
        landing_hero_cta1: 'Start Free Now',
        landing_hero_cta2: 'See Features',
        
        landing_stats_users: '5,000+ Active Users',
        landing_stats_docs: '20,000+ Documents Sent',
        landing_stats_uptime: '99.9% Server Uptime',
        landing_stats_satisfaction: '4.9★ User Satisfaction',

        landing_feat_filter_all: 'All',
        landing_feat_filter_free: 'FREE',
        landing_feat_filter_pro: 'PRO',
        landing_feat_filter_ultimate: 'ULTIMATE',

        features_title: 'Everything you need',
        features_sub: 'From POS cashier to financial reports — all included in one app.',
        pricing_title: 'Start free, upgrade anytime',
        pricing_subtitle: 'Transparent pricing. No hidden fees. Cancel anytime.',

        landing_how_title: 'How It Works',
        landing_how_step1_t: 'Register Free',
        landing_how_step1_d: 'Confirm email & login instantly.',
        landing_how_step2_t: 'Setup Business',
        landing_how_step2_d: 'Upload logo & enter business info.',
        landing_how_step3_t: 'Add Data',
        landing_how_step3_d: 'Add products & client data.',
        landing_how_step4_t: 'Start Selling',
        landing_how_step4_d: 'Send invoices & track reports.',

        landing_pricing_badge_popular: 'Most Popular',
        landing_pricing_badge_ultimate: 'Best for large business',
        landing_pricing_guarantee: '✓ No hidden fees ✓ Cancel anytime ✓ No credit card required',

        landing_faq_q1: 'Is it really free forever?',
        landing_faq_a1: 'Yes, My Invoice\'s FREE plan is genuinely free — no time limits, no hidden conditions, and no surprise charges. You can create invoices, manage clients, and use the POS cashier system at absolutely no cost. Upgrading to PRO or ULTIMATE is only necessary when your business grows and you need advanced features like detailed reports, barcode scanning, or customer loyalty programs.',
        landing_faq_q2: 'How to upgrade to PRO or ULTIMATE?',
        landing_faq_a2: 'Upgrading is simple and can be done anytime directly from within the app. Just navigate to the Upgrade menu in the sidebar, choose the plan that best fits your business needs, and complete the payment via bank transfer or QRIS. Your plan will be activated automatically within minutes after payment is confirmed — no need to contact our team, no waiting, no hassle.',
        landing_faq_q3: 'Is my data safe?',
        landing_faq_a3: 'Your data security is our top priority. All data is stored on encrypted servers with enterprise-grade security standards. We never sell, share, or use your business data for any purpose other than running this service. Every account is protected with secure authentication, and all connections use SSL/HTTPS encryption. Your data belongs to you — always.',
        landing_faq_q4: 'Can I use it on mobile, tablet, or laptop?',
        landing_faq_a4: 'Absolutely. My Invoice is built as a fully responsive web application that works perfectly across all devices — Android and iPhone smartphones, tablets, laptops, and desktop PCs. No app installation required. Simply open your browser, log in, and you\'re ready to work from any device, anytime, anywhere.',
        landing_faq_q5: 'Is there a trial for PRO/ULTIMATE?',
        landing_faq_a5: 'Yes! New users who sign up through a special promo link will receive a 14-day free trial of all PRO and ULTIMATE features — no credit card required. This is your opportunity to experience firsthand how features like in-depth cashier reports, member loyalty programs, and barcode scanning can transform the way you run your business before committing to a subscription.',
        landing_faq_q6: 'What if I forget my password?',
        landing_faq_a6: 'No worries — it\'s a quick fix. On the login page, click the "Forgot Password" button, enter the email address you used when registering, and we\'ll immediately send a password reset link to your inbox. Follow the instructions in the email, and you can create a new password in under 2 minutes. If the email doesn\'t arrive, check your spam folder or contact us via WhatsApp for direct assistance.',
        landing_faq_q7: 'Can clients view invoices without registering?',
        landing_faq_a7: 'Not at all. Your clients can receive invoices as PDF files sent directly via WhatsApp or email — no My Invoice account required. The invoice PDF looks professional with your store logo, complete billing details, and clear payment information. A public invoice link feature that allows clients to view and pay directly via browser is currently under development and coming soon.',
        landing_faq_q8: 'How to contact support?',
        landing_faq_a8: 'We\'re here to help whenever you need us. You can reach us via WhatsApp for the fastest response, or send an email to support@myinvoice.space for more detailed inquiries. Our team operates every day and is committed to responding within 24 hours. You can also fill out the contact form at the bottom of this page and we\'ll get back to you shortly.',

        testimonials_title: 'What they say',
        landing_testi1_text: 'Used to be messy with manual records. Since using My Invoice, sending bills to suppliers is just a click away, and stock is neatly monitored. Highly recommended for small businesses!',
        landing_testi1_name: 'Budi Santoso',
        landing_testi1_role: 'Owner Kopi Kenangan Manis',
        landing_testi2_text: 'The POS cashier feature is very light on mobile. The barcode scanner works smoothly, making the queue much faster. The support via WA is also very friendly.',
        landing_testi2_name: 'Siti Aminah',
        landing_testi2_role: 'Butik Fashion Muslimah',
        landing_testi3_text: 'The financial reports are very comprehensive. I can check daily profit without opening a laptop. Highly recommended for those who want to organize their business admin.',
        landing_testi3_name: 'Andi Wijaya',
        landing_testi3_role: 'Distributor Alat Tulis',

        landing_contact_title: 'Contact Us',
        landing_contact_sub: 'Have questions or need special help? Our team is ready to help your business grow faster.',
        landing_contact_name: 'Name',
        landing_contact_email: 'Email',
        landing_contact_message: 'Message',
        landing_contact_send: 'Send Message',
        landing_contact_wa: 'Chat via WhatsApp',

        landing_final_cta: 'Start now — free forever!',
        landing_final_btn: 'Register Free Now →',
        landing_footer_tagline: 'Manage business easier, get paid faster.',
        landing_footer_services: 'Services',
        landing_footer_company: 'Company',
        landing_footer_policy: 'Privacy Policy',
        landing_footer_terms: 'Terms & Conditions',
        landing_footer_resources: 'Resources',
        landing_footer_blog: 'Articles & Blog',
        landing_footer_made_with: '© 2026 myinvoice.space • Made with ❤️ for Indonesian MSMEs.',
    }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'ID');

    const toggleLang = () => {
        const next = lang === 'ID' ? 'EN' : 'ID';
        setLang(next);
        localStorage.setItem('lang', next);
    };

    const t = (key) => translations[lang][key] || translations['ID'][key] || key;

    return (
        <LanguageContext.Provider value={{ lang, toggleLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLang() {
    return useContext(LanguageContext);
}
